@echo off
setlocal enabledelayedexpansion

:: -- plotviz Windows package builder ------------------------------------------
:: Produces:
::   dist\plotviz\           -- one-folder app (PyInstaller)
::   dist\plotviz-VERSION-setup.exe  -- NSIS installer (if makensis on PATH)
::   dist\plotviz-VERSION-win.zip    -- portable zip   (always)
::
:: Requirements:
::   uv      https://astral.sh/uv
::   NSIS    https://nsis.sourceforge.io  (optional)
::
:: Usage (from repo root):
::   create_pkg_win.bat
:: -----------------------------------------------------------------------------

set "ROOT_DIR=%~dp0"
set "ROOT_DIR=%ROOT_DIR:~0,-1%"
cd /d "%ROOT_DIR%"

echo.
echo ================================================
echo    plotviz Windows package builder
echo    Root : %ROOT_DIR%
echo ================================================

where uv >nul 2>&1
if errorlevel 1 (
    echo [ERROR] uv not found.
    echo         Install: winget install astral-sh.uv
    exit /b 1
)

for /f "tokens=*" %%v in ('uv --version') do set UV_VER=%%v
for /f "tokens=*" %%v in ('uv run python --version') do set PY_VER=%%v
echo    uv     : %UV_VER%
echo    Python : %PY_VER%

for /f "tokens=*" %%v in ('uv run python -c "import sys,pathlib;sys.path.insert(0,str(pathlib.Path(\"src/plotviz\"))); from config._version import __version__;print(__version__)"') do set VERSION=%%v
echo    Version: %VERSION%

set "APP_NAME=plotviz"
set "SPEC_FILE=plotviz_win.spec"
set "DIST_DIR=dist"
set "ASSETS_DIR=assets"
set "ICON_ICO=%ASSETS_DIR%\plotviz.ico"
set "APP_DIR=%DIST_DIR%\%APP_NAME%"
set "EXE=%APP_DIR%\%APP_NAME%.exe"
set "ZIP_OUT=%DIST_DIR%\%APP_NAME%-%VERSION%-win.zip"
set "INSTALLER_OUT=%DIST_DIR%\%APP_NAME%-%VERSION%-setup.exe"
set "NSIS_SCRIPT=%DIST_DIR%\installer.nsi"

echo.
echo ^> Syncing dependencies...
uv sync
if errorlevel 1 ( echo [ERROR] uv sync failed & exit /b 1 )

for /f "tokens=*" %%v in ('uv run pyinstaller --version') do set PI_VER=%%v
echo.
echo ^> PyInstaller %PI_VER%

echo.
echo ^> Converting app icon to .ico...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('ZnJvbSBQSUwgaW1wb3J0IEltYWdlCmltcG9ydCBpbywgc3RydWN0LCBwYXRobGliLCBzeXMKCmljbnMgPSBwYXRobGliLlBhdGgoImFzc2V0cy9wbG90dml6LmljbnMiKQppY28gID0gcGF0aGxpYi5QYXRoKCJhc3NldHMvcGxvdHZpei5pY28iKQoKaWYgbm90IGljbnMuZXhpc3RzKCk6CiAgICBwcmludCgiICBXQVJOSU5HOiBwbG90dml6LmljbnMgbm90IGZvdW5kIC0tIHNraXBwaW5nIC5pY28gY29udmVyc2lvbiIpCiAgICBzeXMuZXhpdCgwKQoKZGF0YSA9IGljbnMucmVhZF9ieXRlcygpCnBvcyA9IDgKYmVzdCwgYmVzdF9weCA9IE5vbmUsIDAKd2hpbGUgcG9zIDwgbGVuKGRhdGEpOgogICAgc2l6ZSA9IHN0cnVjdC51bnBhY2soIj5JIiwgZGF0YVtwb3MrNDpwb3MrOF0pWzBdCiAgICBwYXlsb2FkID0gZGF0YVtwb3MrODpwb3Mrc2l6ZV0KICAgIGlmIHBheWxvYWRbOjhdID09IGIiXHg4OVBOR1xyXG5ceDFhXG4iOgogICAgICAgIGltZyA9IEltYWdlLm9wZW4oaW8uQnl0ZXNJTyhwYXlsb2FkKSkKICAgICAgICBpZiBpbWcuc2l6ZVswXSAqIGltZy5zaXplWzFdID4gYmVzdF9weDoKICAgICAgICAgICAgYmVzdCwgYmVzdF9weCA9IHBheWxvYWQsIGltZy5zaXplWzBdICogaW1nLnNpemVbMV0KICAgIHBvcyArPSBzaXplCgppZiBiZXN0IGlzIE5vbmU6CiAgICBwcmludCgiICBXQVJOSU5HOiBubyBQTkcgZm91bmQgaW4gLmljbnMgLS0gc2tpcHBpbmcgLmljbyBjb252ZXJzaW9uIikKICAgIHN5cy5leGl0KDApCgpzcmMgPSBJbWFnZS5vcGVuKGlvLkJ5dGVzSU8oYmVzdCkpLmNvbnZlcnQoIlJHQkEiKQpzaXplcyA9IFsxNiwgMzIsIDQ4LCA2NCwgMTI4LCAyNTZdCmltZ3MgID0gW3NyYy5yZXNpemUoKHMsIHMpLCBJbWFnZS5MQU5DWk9TKSBmb3IgcyBpbiBzaXplc10KaW1nc1swXS5zYXZlKHN0cihpY28pLCBmb3JtYXQ9IklDTyIsIHNpemVzPVsocywgcykgZm9yIHMgaW4gc2l6ZXNdLAogICAgICAgICAgICAgYXBwZW5kX2ltYWdlcz1pbWdzWzE6XSkKcHJpbnQoZiIgIHBsb3R2aXouaWNvIHdyaXR0ZW4gKHtsZW4oc2l6ZXMpfSBzaXplcykiKQ==').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
echo ^> Generating file-type icons (.ico)...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('ZnJvbSBQSUwgaW1wb3J0IEltYWdlLCBJbWFnZURyYXcsIEltYWdlRm9udAppbXBvcnQgaW8sIHN0cnVjdCwgcGF0aGxpYiwgc3lzCgpkZWYgZXh0cmFjdF9iYXNlKGljbnNfcGF0aCk6CiAgICBkYXRhID0gaWNuc19wYXRoLnJlYWRfYnl0ZXMoKQogICAgcG9zLCBiZXN0LCBiZXN0X3B4ID0gOCwgTm9uZSwgMAogICAgd2hpbGUgcG9zIDwgbGVuKGRhdGEpOgogICAgICAgIHNpemUgPSBzdHJ1Y3QudW5wYWNrKCI+SSIsIGRhdGFbcG9zKzQ6cG9zKzhdKVswXQogICAgICAgIHBheWxvYWQgPSBkYXRhW3Bvcys4OnBvcytzaXplXQogICAgICAgIGlmIHBheWxvYWRbOjhdID09IGIiXHg4OVBOR1xyXG5ceDFhXG4iOgogICAgICAgICAgICBpbWcgPSBJbWFnZS5vcGVuKGlvLkJ5dGVzSU8ocGF5bG9hZCkpCiAgICAgICAgICAgIGlmIGltZy5zaXplWzBdKmltZy5zaXplWzFdID4gYmVzdF9weDoKICAgICAgICAgICAgICAgIGJlc3QsIGJlc3RfcHggPSBwYXlsb2FkLCBpbWcuc2l6ZVswXSppbWcuc2l6ZVsxXQogICAgICAgIHBvcyArPSBzaXplCiAgICByZXR1cm4gSW1hZ2Uub3Blbihpby5CeXRlc0lPKGJlc3QpKS5jb252ZXJ0KCJSR0JBIikgaWYgYmVzdCBlbHNlIE5vbmUKCmRlZiBtYWtlX2RvY19pY29uKGJhc2UsIGJhbm5lcl9yZ2IsIGxhYmVsKToKICAgIFMgPSAyNTYKICAgIGltZyAgPSBJbWFnZS5uZXcoIlJHQkEiLCAoUywgUyksICgwLDAsMCwwKSkKICAgIGRyYXcgPSBJbWFnZURyYXcuRHJhdyhpbWcpCiAgICBSLCBGT0xELCBCQU5ORVJfSCA9IDE2LCAzNiwgNDAKICAgIHBsLHByLHB0LHBiID0gOCwgUy04LCA2LCBTLTYKICAgIGRyYXcucm91bmRlZF9yZWN0YW5nbGUoW3BsLHB0LHByLHBiXSwgcmFkaXVzPVIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBmaWxsPSgyNTUsMjU1LDI1NSwyNTUpLCBvdXRsaW5lPSgyMDAsMjAwLDIxMCwyNTUpLCB3aWR0aD0yKQogICAgZngsIGZ5ID0gcHItRk9MRCwgcHQrRk9MRAogICAgZHJhdy5wb2x5Z29uKFsoZngscHQpLChwcixwdCksKHByLGZ5KV0sIGZpbGw9KDAsMCwwLDApKQogICAgZHJhdy5wb2x5Z29uKFsoZngscHQpLChwcixmeSksKGZ4LGZ5KV0sIGZpbGw9KDIxOCwyMTgsMjMyLDI1NSkpCiAgICBkcmF3LmxpbmUoWyhmeCxwdCksKGZ4LGZ5KSwocHIsZnkpXSwgZmlsbD0oMTc1LDE3NSwyMDAsMjU1KSwgd2lkdGg9MikKICAgIGRyYXcubGluZShbKGZ4LHB0KSwocHIsZnkpXSwgZmlsbD0oMjAwLDIwMCwyMTUsMjU1KSwgd2lkdGg9MikKICAgIGFydCA9IGJhc2UuY29weSgpOyBhcnQudGh1bWJuYWlsKChmeC1wbC0xMiwgcGItQkFOTkVSX0gtcHQtMTIpLCBJbWFnZS5MQU5DWk9TKQogICAgY3ggPSBwbCs2KyhmeC1wbC0xMi1hcnQud2lkdGgpLy8yOyBjeSA9IHB0KzYrKHBiLUJBTk5FUl9ILXB0LTEyLWFydC5oZWlnaHQpLy8yCiAgICBpbWcuYWxwaGFfY29tcG9zaXRlKGFydCwgKGN4LGN5KSkKICAgIGRyYXcgPSBJbWFnZURyYXcuRHJhdyhpbWcpCiAgICBwYWdlX21hc2sgPSBJbWFnZS5uZXcoIlJHQkEiLChTLFMpLCgwLDAsMCwwKSkKICAgIEltYWdlRHJhdy5EcmF3KHBhZ2VfbWFzaykucm91bmRlZF9yZWN0YW5nbGUoW3BsLHB0LHByLHBiXSxyYWRpdXM9UixmaWxsPSgyNTUsMjU1LDI1NSwyNTUpKQogICAgYmFubmVyID0gSW1hZ2UubmV3KCJSR0JBIiwoUyxTKSwoMCwwLDAsMCkpCiAgICBJbWFnZURyYXcuRHJhdyhiYW5uZXIpLnJlY3RhbmdsZShbcGwscGItQkFOTkVSX0gscHIscGJdLGZpbGw9KCpiYW5uZXJfcmdiLDI1NSkpCiAgICBjbGlwcGVkID0gSW1hZ2UubmV3KCJSR0JBIiwoUyxTKSwoMCwwLDAsMCkpCiAgICBjbGlwcGVkLnBhc3RlKGJhbm5lciwgbWFzaz1wYWdlX21hc2suc3BsaXQoKVszXSkKICAgIGltZyA9IEltYWdlLmFscGhhX2NvbXBvc2l0ZShpbWcsIGNsaXBwZWQpCiAgICBkcmF3ID0gSW1hZ2VEcmF3LkRyYXcoaW1nKQogICAgdHJ5OgogICAgICAgIGZvbnQgPSBJbWFnZUZvbnQudHJ1ZXR5cGUoIkM6L1dpbmRvd3MvRm9udHMvYXJpYWxiZC50dGYiLCAyMikKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgZm9udCA9IEltYWdlRm9udC5sb2FkX2RlZmF1bHQoKQogICAgYmIgPSBkcmF3LnRleHRiYm94KCgwLDApLCBsYWJlbCwgZm9udD1mb250KQogICAgdHcsdGggPSBiYlsyXS1iYlswXSwgYmJbM10tYmJbMV0KICAgIHR4ID0gKHBsK3ByKS8vMiAtIHR3Ly8yCiAgICB0eSA9IHBiLUJBTk5FUl9IICsgKEJBTk5FUl9ILXRoKS8vMiAtIGJiWzFdCiAgICBkcmF3LnRleHQoKHR4LHR5KSwgbGFiZWwsIGZvbnQ9Zm9udCwgZmlsbD0oMjU1LDI1NSwyNTUsMjU1KSkKICAgIHJldHVybiBpbWcKCmljbnMgPSBwYXRobGliLlBhdGgoImFzc2V0cy9wbG90dml6LmljbnMiKQppZiBub3QgaWNucy5leGlzdHMoKToKICAgIHByaW50KCIgIFdBUk5JTkc6IHBsb3R2aXouaWNucyBub3QgZm91bmQgLS0gc2tpcHBpbmcgZmlsZS10eXBlIGljb25zIikKICAgIHN5cy5leGl0KDApCgpiYXNlID0gZXh0cmFjdF9iYXNlKGljbnMpCmlmIGJhc2UgaXMgTm9uZToKICAgIHByaW50KCIgIFdBUk5JTkc6IGNvdWxkIG5vdCBleHRyYWN0IGJhc2UgYXJ0IC0tIHNraXBwaW5nIik7IHN5cy5leGl0KDApCgpUWVBFUyA9IFsKICAgICgicHZpeiIsICAoIDUyLDEyMCwyMjApLCAiLnB2aXoiKSwKICAgICgicHZpenQiLCAoMjEwLDEzMCwgMjApLCAiLnB2aXp0IiksCiAgICAoInB2aXp4IiwgKDE0MCwgNjAsMjAwKSwgIi5wdml6eCIpLApdCmljb19zaXplcyA9IFsxNiwzMiw0OCw2NCwxMjgsMjU2XQpmb3Igc3RlbSwgcmdiLCBsYWJlbCBpbiBUWVBFUzoKICAgIGljb24yNTYgPSBtYWtlX2RvY19pY29uKGJhc2UsIHJnYiwgbGFiZWwpCiAgICBpbWdzID0gW2ljb24yNTYucmVzaXplKChzLHMpLCBJbWFnZS5MQU5DWk9TKSBmb3IgcyBpbiBpY29fc2l6ZXNdCiAgICBvdXQgPSBwYXRobGliLlBhdGgoZiJhc3NldHMve3N0ZW19LmljbyIpCiAgICBpbWdzWzBdLnNhdmUoc3RyKG91dCksIGZvcm1hdD0iSUNPIiwgc2l6ZXM9WyhzLHMpIGZvciBzIGluIGljb19zaXplc10sCiAgICAgICAgICAgICAgICAgYXBwZW5kX2ltYWdlcz1pbWdzWzE6XSkKICAgIHByaW50KGYiICB7b3V0fSB3cml0dGVuIik=').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
echo ^> Writing %SPEC_FILE%...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('aW1wb3J0IHBhdGhsaWIsIHRleHR3cmFwCgpST09UID0gcGF0aGxpYi5QYXRoKCIuIikKCnNwZWMgPSAiIiIjIC0qLSBtb2RlOiBweXRob24gOyBjb2Rpbmc6IHV0Zi04IC0qLQojIHBsb3R2aXpfd2luLnNwZWMgLS0gUHlJbnN0YWxsZXIgc3BlYyBmb3IgV2luZG93cwojIEF1dG8tZ2VuZXJhdGVkIGJ5IGNyZWF0ZV9wa2dfd2luLmJhdCAtLSBkbyBub3QgZWRpdCBieSBoYW5kLgoKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCmZyb20gUHlJbnN0YWxsZXIudXRpbHMuaG9va3MgaW1wb3J0IGNvbGxlY3RfZGF0YV9maWxlcywgY29sbGVjdF9zdWJtb2R1bGVzCmltcG9ydCBpbXBvcnRsaWIudXRpbCBhcyBfaWx1CgpfdnNwZWMgPSBQYXRoKFNQRUNQQVRIKSAvICJzcmMiIC8gInBsb3R2aXoiIC8gImNvbmZpZyIgLyAiX3ZlcnNpb24ucHkiCl92bW9kICA9IF9pbHUuc3BlY19mcm9tX2ZpbGVfbG9jYXRpb24oIl92ZXJzaW9uIiwgX3ZzcGVjKQpfdm0gICAgPSBfaWx1Lm1vZHVsZV9mcm9tX3NwZWMoX3Ztb2QpOyBfdm1vZC5sb2FkZXIuZXhlY19tb2R1bGUoX3ZtKQpBUFBfVkVSU0lPTiA9IF92bS5fX3ZlcnNpb25fXwoKUk9PVF9ESVIgPSBQYXRoKFNQRUNQQVRIKQpQS0dfRElSICA9IFJPT1RfRElSIC8gInNyYyIgLyAicGxvdHZpeiIKCmhpZGRlbl9pbXBvcnRzID0gWwogICAgIlB5UXQ2IiwgIlB5UXQ2LlF0V2lkZ2V0cyIsICJQeVF0Ni5RdENvcmUiLCAiUHlRdDYuUXRHdWkiLAogICAgIlB5UXQ2LlF0UHJpbnRTdXBwb3J0IiwgIlB5UXQ2LnNpcCIsCiAgICAibWF0cGxvdGxpYiIsICJtYXRwbG90bGliLnB5cGxvdCIsCiAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX3F0NWFnZyIsCiAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX3F0YWdnIiwKICAgICJtYXRwbG90bGliLmJhY2tlbmRzLmJhY2tlbmRfYWdnIiwKICAgICJtYXRwbG90bGliLmJhY2tlbmRzLmJhY2tlbmRfc3ZnIiwKICAgICJtYXRwbG90bGliLmJhY2tlbmRzLmJhY2tlbmRfcGRmIiwKICAgICJtYXRwbG90bGliLmZpZ3VyZSIsICJtYXRwbG90bGliLnRpY2tlciIsICJtYXRwbG90bGliLmNvbG9ycyIsCiAgICAibWF0cGxvdGxpYi5jbSIsICJtYXRwbG90bGliLnBhdGNoZXMiLCAibWF0cGxvdGxpYi5saW5lcyIsCiAgICAibWF0cGxvdGxpYi5jb2xsZWN0aW9ucyIsICJtYXRwbG90bGliLmNvbnRvdXIiLCAibWF0cGxvdGxpYi5pbWFnZSIsCiAgICAibWF0cGxvdGxpYi5heGVzLl9heGVzIiwgIm1hdHBsb3RsaWIuYXhlcy5fYmFzZSIsCiAgICAibWF0cGxvdGxpYi5heGVzLl9zZWNvbmRhcnlfYXhlcyIsCiAgICAibXBsX3Rvb2xraXRzIiwgIm1wbF90b29sa2l0cy5tcGxvdDNkIiwKICAgICJtcGxfdG9vbGtpdHMubXBsb3QzZC5heGVzM2QiLCAibXBsX3Rvb2xraXRzLm1wbG90M2QuYXJ0M2QiLAogICAgIm51bXB5IiwgIm51bXB5LmNvcmUuX211bHRpYXJyYXlfdW1hdGgiLCAibnVtcHkuY29yZS5tdWx0aWFycmF5IiwKICAgICJudW1weS5yYW5kb20iLCAibnVtcHkuZmZ0IiwgIm51bXB5LmxpbmFsZyIsCiAgICAic2NpcHkiLCAic2NpcHkub3B0aW1pemUiLCAic2NpcHkuc3RhdHMiLCAic2NpcHkuaW50ZXJwb2xhdGUiLAogICAgInNjaXB5LnNwZWNpYWwiLCAic2NpcHkubGluYWxnIiwKICAgICJzY2lweS5fbGliLm1lc3NhZ2VzdHJlYW0iLCAic2NpcHkuX2xpYi5fdXRpbCIsCiAgICAicGFuZGFzIiwKICAgICJwYW5kYXMuX2xpYnMudHNsaWJzLm5wX2RhdGV0aW1lIiwgInBhbmRhcy5fbGlicy50c2xpYnMubmF0dHlwZSIsCiAgICAicGFuZGFzLl9saWJzLnRzbGlicy50aW1lZGVsdGFzIiwgInBhbmRhcy5fbGlicy50c2xpYnMudGltZXN0YW1wcyIsCiAgICAicGFuZGFzLl9saWJzLnRzbGlicy5vZmZzZXRzIiwgInBhbmRhcy5fbGlicy50c2xpYnMucGVyaW9kIiwKICAgICJwYW5kYXMuX2xpYnMudHNsaWJzLnRpbWV6b25lcyIsICJwYW5kYXMuX2xpYnMubWlzc2luZyIsCiAgICAicGFuZGFzLmlvLmZvcm1hdHMuc3R5bGUiLCAicGFuZGFzLmlvLmV4Y2VsLl9vcGVucHl4bCIsCiAgICAib3BlbnB5eGwiLCAib3BlbnB5eGwuY2VsbC5fd3JpdGVyIiwgIm9wZW5weXhsLnN0eWxlcyIsCiAgICAib3BlbnB5eGwucmVhZGVyLmV4Y2VsIiwgIm9wZW5weXhsLndyaXRlci5leGNlbCIsCiAgICAib3BlbnB5eGwudXRpbHMiLCAib3BlbnB5eGwudXRpbHMuZGF0YWZyYW1lIiwKICAgICJ1aSIsICJ1aS5tYWluX3dpbmRvdyIsICJ1aS50YWJfYnVpbGRlcnMiLCAidWkucGxvdF9lbmdpbmUiLAogICAgInVpLnNlcmlhbGl6YXRpb24iLCAidWkuY2FudmFzIiwKICAgICJkYXRhIiwgImRhdGEubG9hZGVyIiwgImRhdGEuc2NpZW50aWZpYyIsCiAgICAic3R5bGluZyIsICJzdHlsaW5nLnByZXNldHMiLAogICAgImNvbmZpZyIsICJjb25maWcuc2V0dGluZ3MiLCAiY29uZmlnLl92ZXJzaW9uIiwKICAgICJ6aXBmaWxlIiwgImpzb24iLCAidGVtcGZpbGUiLCAidHJhY2ViYWNrIiwKICAgICJtdWx0aXByb2Nlc3NpbmciLCAibXVsdGlwcm9jZXNzaW5nLnBvb2wiLAogICAgIndpbnJlZyIsCl0KCmhpZGRlbl9pbXBvcnRzICs9IGNvbGxlY3Rfc3VibW9kdWxlcygibWF0cGxvdGxpYiIpCmhpZGRlbl9pbXBvcnRzICs9IGNvbGxlY3Rfc3VibW9kdWxlcygibXBsX3Rvb2xraXRzIikKaGlkZGVuX2ltcG9ydHMgKz0gY29sbGVjdF9zdWJtb2R1bGVzKCJzY2lweSIpCmhpZGRlbl9pbXBvcnRzICs9IGNvbGxlY3Rfc3VibW9kdWxlcygicGFuZGFzIikKaGlkZGVuX2ltcG9ydHMgKz0gY29sbGVjdF9zdWJtb2R1bGVzKCJvcGVucHl4bCIpCmhpZGRlbl9pbXBvcnRzICs9IGNvbGxlY3Rfc3VibW9kdWxlcygiUHlRdDYiKQoKZGF0YXMgPSBbXQpfYXNzZXRzID0gUk9PVF9ESVIgLyAiYXNzZXRzIgppZiBfYXNzZXRzLmV4aXN0cygpOgogICAgZGF0YXMgKz0gWyhzdHIoX2Fzc2V0cyksICJhc3NldHMiKV0KZGF0YXMgKz0gY29sbGVjdF9kYXRhX2ZpbGVzKCJtYXRwbG90bGliIikKZGF0YXMgKz0gY29sbGVjdF9kYXRhX2ZpbGVzKCJtcGxfdG9vbGtpdHMiKQpkYXRhcyArPSBjb2xsZWN0X2RhdGFfZmlsZXMoInBhbmRhcyIpCmRhdGFzICs9IGNvbGxlY3RfZGF0YV9maWxlcygib3BlbnB5eGwiKQpkYXRhcyArPSBjb2xsZWN0X2RhdGFfZmlsZXMoInNjaXB5IikKCl9pY28gPSBST09UX0RJUiAvICJhc3NldHMiIC8gInBsb3R2aXouaWNvIgpfaWNvbl9hcmcgPSBzdHIoX2ljbykgaWYgX2ljby5leGlzdHMoKSBlbHNlIE5vbmUKCmEgPSBBbmFseXNpcygKICAgIFtzdHIoUEtHX0RJUiAvICJtYWluLnB5IildLAogICAgcGF0aGV4PVtzdHIoUEtHX0RJUildLAogICAgYmluYXJpZXM9W10sCiAgICBkYXRhcz1kYXRhcywKICAgIGhpZGRlbmltcG9ydHM9aGlkZGVuX2ltcG9ydHMsCiAgICBob29rc3BhdGg9W10sCiAgICBob29rc2NvbmZpZz17fSwKICAgIHJ1bnRpbWVfaG9va3M9W10sCiAgICBleGNsdWRlcz1bCiAgICAgICAgInRraW50ZXIiLCAiX3RraW50ZXIiLAogICAgICAgICJQeVF0NSIsICJQeVNpZGUyIiwgIlB5U2lkZTYiLCAid3giLCAiZ2kiLAogICAgICAgICJJUHl0aG9uIiwgImp1cHl0ZXIiLCAibm90ZWJvb2siLAogICAgICAgICJweXRlc3QiLCAic3BoaW54IiwgImRvY3V0aWxzIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX2d0azNhZ2ciLAogICAgICAgICJtYXRwbG90bGliLmJhY2tlbmRzLmJhY2tlbmRfZ3RrM2NhaXJvIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX3d4YWdnIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX3RrYWdnIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX25iYWdnIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5fYmFja2VuZF90ayIsCiAgICBdLAogICAgbm9hcmNoaXZlPUZhbHNlLAopCgpweXogPSBQWVooYS5wdXJlLCBhLnppcHBlZF9kYXRhKQoKZXhlID0gRVhFKAogICAgcHl6LCBhLnNjcmlwdHMsIFtdLAogICAgZXhjbHVkZV9iaW5hcmllcz1UcnVlLAogICAgbmFtZT0icGxvdHZpeiIsCiAgICBkZWJ1Zz1GYWxzZSwKICAgIGJvb3Rsb2FkZXJfaWdub3JlX3NpZ25hbHM9RmFsc2UsCiAgICBzdHJpcD1GYWxzZSwKICAgIHVweD1GYWxzZSwKICAgIGNvbnNvbGU9RmFsc2UsCiAgICBpY29uPV9pY29uX2FyZywKICAgIHZlcnNpb25fZmlsZT1Ob25lLAopCgpjb2xsID0gQ09MTEVDVCgKICAgIGV4ZSwgYS5iaW5hcmllcywgYS56aXBmaWxlcywgYS5kYXRhcywKICAgIHN0cmlwPUZhbHNlLCB1cHg9RmFsc2UsIHVweF9leGNsdWRlPVtdLAogICAgbmFtZT0icGxvdHZpeiIsCikKIiIiCgpwYXRobGliLlBhdGgoInBsb3R2aXpfd2luLnNwZWMiKS53cml0ZV90ZXh0KHNwZWMubHN0cmlwKCksIGVuY29kaW5nPSJ1dGYtOCIpCnByaW50KCIgIHBsb3R2aXpfd2luLnNwZWMgd3JpdHRlbiIp').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
echo ^> Cleaning previous build...
if exist build                     rmdir /s /q build
if exist "%DIST_DIR%\%APP_NAME%"  rmdir /s /q "%DIST_DIR%\%APP_NAME%"

echo.
echo ^> Building %APP_NAME%.exe...
uv run pyinstaller "%SPEC_FILE%" --noconfirm --clean --log-level WARN
if errorlevel 1 (
    echo [ERROR] PyInstaller build failed.
    echo         Retry: uv run pyinstaller %SPEC_FILE% --noconfirm --clean --log-level DEBUG
    exit /b 1
)

if not exist "%EXE%" (
    echo [ERROR] Build failed -- %EXE% not found.
    exit /b 1
)
echo    %APP_NAME%.exe found.

echo.
echo ^> Writing file-association registry script...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('aW1wb3J0IHBhdGhsaWIKCnJlZyA9IHBhdGhsaWIuUGF0aCgiZGlzdC9wbG90dml6L3JlZ2lzdGVyX2ZpbGV0eXBlcy5yZWciKQpjb250ZW50ID0gKAogICAgIldpbmRvd3MgUmVnaXN0cnkgRWRpdG9yIFZlcnNpb24gNS4wMFxyXG5cclxuIgogICAgIjsgcGxvdHZpeiBmaWxlLXR5cGUgYXNzb2NpYXRpb25zXHJcbiIKICAgICI7IERvdWJsZS1jbGljayB0aGlzIGZpbGUgKG9yIHJ1biBhcyBBZG1pbmlzdHJhdG9yKSB0byByZWdpc3Rlci5cclxuXHJcbiIKICAgICJbSEtFWV9DTEFTU0VTX1JPT1RcXC5wdml6XVxyXG4iCiAgICAiQD1cInBsb3R2aXouQ2hhcnRcIlxyXG5cclxuIgogICAgIltIS0VZX0NMQVNTRVNfUk9PVFxccGxvdHZpei5DaGFydF1cclxuIgogICAgIkA9XCJwbG90dml6IENoYXJ0XCJcclxuXHJcbiIKICAgICJbSEtFWV9DTEFTU0VTX1JPT1RcXHBsb3R2aXouQ2hhcnRcXERlZmF1bHRJY29uXVxyXG4iCiAgICAiQD1cIlxcXCJDOlxcXFxQcm9ncmFtIEZpbGVzXFxcXHBsb3R2aXpcXFxccGxvdHZpei5leGVcXFwiLDBcIlxyXG5cclxuIgogICAgIltIS0VZX0NMQVNTRVNfUk9PVFxccGxvdHZpei5DaGFydFxcc2hlbGxcXG9wZW5cXGNvbW1hbmRdXHJcbiIKICAgICJAPVwiXFxcIkM6XFxcXFByb2dyYW0gRmlsZXNcXFxccGxvdHZpelxcXFxwbG90dml6LmV4ZVxcXCIgXFxcIiUxXFxcIlwiXHJcblxyXG4iCiAgICAiW0hLRVlfQ0xBU1NFU19ST09UXFwucHZpenRdXHJcbiIKICAgICJAPVwicGxvdHZpei5UZW1wbGF0ZVwiXHJcblxyXG4iCiAgICAiW0hLRVlfQ0xBU1NFU19ST09UXFxwbG90dml6LlRlbXBsYXRlXVxyXG4iCiAgICAiQD1cInBsb3R2aXogVGVtcGxhdGVcIlxyXG5cclxuIgogICAgIltIS0VZX0NMQVNTRVNfUk9PVFxccGxvdHZpei5UZW1wbGF0ZVxcRGVmYXVsdEljb25dXHJcbiIKICAgICJAPVwiXFxcIkM6XFxcXFByb2dyYW0gRmlsZXNcXFxccGxvdHZpelxcXFxwbG90dml6LmV4ZVxcXCIsMFwiXHJcblxyXG4iCiAgICAiW0hLRVlfQ0xBU1NFU19ST09UXFxwbG90dml6LlRlbXBsYXRlXFxzaGVsbFxcb3BlblxcY29tbWFuZF1cclxuIgogICAgIkA9XCJcXFwiQzpcXFxcUHJvZ3JhbSBGaWxlc1xcXFxwbG90dml6XFxcXHBsb3R2aXouZXhlXFxcIiBcXFwiJTFcXFwiXCJcclxuXHJcbiIKICAgICJbSEtFWV9DTEFTU0VTX1JPT1RcXC5wdml6eF1cclxuIgogICAgIkA9XCJwbG90dml6LlBhbGV0dGVCdW5kbGVcIlxyXG5cclxuIgogICAgIltIS0VZX0NMQVNTRVNfUk9PVFxccGxvdHZpei5QYWxldHRlQnVuZGxlXVxyXG4iCiAgICAiQD1cInBsb3R2aXogUGFsZXR0ZSBCdW5kbGVcIlxyXG5cclxuIgogICAgIltIS0VZX0NMQVNTRVNfUk9PVFxccGxvdHZpei5QYWxldHRlQnVuZGxlXFxEZWZhdWx0SWNvbl1cclxuIgogICAgIkA9XCJcXFwiQzpcXFxcUHJvZ3JhbSBGaWxlc1xcXFxwbG90dml6XFxcXHBsb3R2aXouZXhlXFxcIiwwXCJcclxuXHJcbiIKICAgICJbSEtFWV9DTEFTU0VTX1JPT1RcXHBsb3R2aXouUGFsZXR0ZUJ1bmRsZVxcc2hlbGxcXG9wZW5cXGNvbW1hbmRdXHJcbiIKICAgICJAPVwiXFxcIkM6XFxcXFByb2dyYW0gRmlsZXNcXFxccGxvdHZpelxcXFxwbG90dml6LmV4ZVxcXCIgXFxcIiUxXFxcIlwiXHJcbiIKKQpyZWcud3JpdGVfdGV4dChjb250ZW50LCBlbmNvZGluZz0idXRmLTE2IikKcHJpbnQoZiIgIHtyZWd9IHdyaXR0ZW4iKQ==').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
echo ^> Writing NSIS installer script...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('aW1wb3J0IHBhdGhsaWIKCnZlcnNpb24gPSBvcGVuKCJzcmMvcGxvdHZpei9jb25maWcvX3ZlcnNpb24ucHkiKS5yZWFkKCkuc3BsaXQoY2hyKDM0KSlbMV0KbnNpID0gcGF0aGxpYi5QYXRoKCJkaXN0L2luc3RhbGxlci5uc2kiKQoKbGluZXMgPSBbCiAgICBmJ05hbWUgInBsb3R2aXoge3ZlcnNpb259IicsCiAgICBmJ091dEZpbGUgInBsb3R2aXote3ZlcnNpb259LXNldHVwLmV4ZSInLAogICAgJ0luc3RhbGxEaXIgIiRQUk9HUkFNRklMRVM2NFxccGxvdHZpeiInLAogICAgJ0luc3RhbGxEaXJSZWdLZXkgSEtMTSAiU29mdHdhcmVcXHBsb3R2aXoiICJJbnN0YWxsX0RpciInLAogICAgJ1JlcXVlc3RFeGVjdXRpb25MZXZlbCBhZG1pbicsCiAgICAnU2V0Q29tcHJlc3NvciAvU09MSUQgbHptYScsCiAgICAnJywKICAgICchaW5jbHVkZSAiTVVJMi5uc2giJywKICAgICchZGVmaW5lIE1VSV9BQk9SVFdBUk5JTkcnLAogICAgJyFkZWZpbmUgTVVJX0lDT04gIi4uXFxhc3NldHNcXHBsb3R2aXouaWNvIicsCiAgICAnIWRlZmluZSBNVUlfVU5JQ09OICIuLlxcYXNzZXRzXFxwbG90dml6LmljbyInLAogICAgJyFpbnNlcnRtYWNybyBNVUlfUEFHRV9XRUxDT01FJywKICAgICchaW5zZXJ0bWFjcm8gTVVJX1BBR0VfRElSRUNUT1JZJywKICAgICchaW5zZXJ0bWFjcm8gTVVJX1BBR0VfSU5TVEZJTEVTJywKICAgICchaW5zZXJ0bWFjcm8gTVVJX1BBR0VfRklOSVNIJywKICAgICchaW5zZXJ0bWFjcm8gTVVJX1VOUEFHRV9DT05GSVJNJywKICAgICchaW5zZXJ0bWFjcm8gTVVJX1VOUEFHRV9JTlNURklMRVMnLAogICAgJyFpbnNlcnRtYWNybyBNVUlfTEFOR1VBR0UgIkVuZ2xpc2giJywKICAgICcnLAogICAgJ1NlY3Rpb24gInBsb3R2aXogKHJlcXVpcmVkKSIgU2VjTWFpbicsCiAgICAnICBTZWN0aW9uSW4gUk8nLAogICAgJyAgU2V0T3V0UGF0aCAiJElOU1RESVIiJywKICAgICcgIEZpbGUgL3IgInBsb3R2aXpcXCouKiInLAogICAgJycsCiAgICAnICBXcml0ZVVuaW5zdGFsbGVyICIkSU5TVERJUlxcVW5pbnN0YWxsLmV4ZSInLAogICAgJycsCiAgICAnICBXcml0ZVJlZ1N0ciBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiRGlzcGxheU5hbWUiICJwbG90dml6IicsCiAgICBmJyAgV3JpdGVSZWdTdHIgSEtMTSAiU29mdHdhcmVcXE1pY3Jvc29mdFxcV2luZG93c1xcQ3VycmVudFZlcnNpb25cXFVuaW5zdGFsbFxccGxvdHZpeiIgIkRpc3BsYXlWZXJzaW9uIiAie3ZlcnNpb259IicsCiAgICAnICBXcml0ZVJlZ1N0ciBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiVW5pbnN0YWxsU3RyaW5nIiAiJElOU1RESVJcXFVuaW5zdGFsbC5leGUiJywKICAgICcgIFdyaXRlUmVnU3RyIEhLTE0gIlNvZnR3YXJlXFxNaWNyb3NvZnRcXFdpbmRvd3NcXEN1cnJlbnRWZXJzaW9uXFxVbmluc3RhbGxcXHBsb3R2aXoiICJJbnN0YWxsTG9jYXRpb24iICIkSU5TVERJUiInLAogICAgJyAgV3JpdGVSZWdTdHIgSEtMTSAiU29mdHdhcmVcXE1pY3Jvc29mdFxcV2luZG93c1xcQ3VycmVudFZlcnNpb25cXFVuaW5zdGFsbFxccGxvdHZpeiIgIlB1Ymxpc2hlciIgIlBhdWxvIENhY2hpbSInLAogICAgJyAgV3JpdGVSZWdEV09SRCBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiTm9Nb2RpZnkiIDEnLAogICAgJyAgV3JpdGVSZWdEV09SRCBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiTm9SZXBhaXIiIDEnLAogICAgJycsCiAgICAnICBDcmVhdGVEaXJlY3RvcnkgIiRTTVBST0dSQU1TXFxwbG90dml6IicsCiAgICAnICBDcmVhdGVTaG9ydGN1dCAiJFNNUFJPR1JBTVNcXHBsb3R2aXpcXHBsb3R2aXoubG5rIiAiJElOU1RESVJcXHBsb3R2aXouZXhlIicsCiAgICAnICBDcmVhdGVTaG9ydGN1dCAiJFNNUFJPR1JBTVNcXHBsb3R2aXpcXFVuaW5zdGFsbC5sbmsiICIkSU5TVERJUlxcVW5pbnN0YWxsLmV4ZSInLAogICAgJyAgQ3JlYXRlU2hvcnRjdXQgIiRERVNLVE9QXFxwbG90dml6LmxuayIgIiRJTlNURElSXFxwbG90dml6LmV4ZSInLAogICAgJycsCiAgICAnICBXcml0ZVJlZ1N0ciBIS0NSICIucHZpeiIgIiIgInBsb3R2aXouQ2hhcnQiJywKICAgICcgIFdyaXRlUmVnU3RyIEhLQ1IgInBsb3R2aXouQ2hhcnQiICIiICJwbG90dml6IENoYXJ0IicsCiAgICAnICBXcml0ZVJlZ1N0ciBIS0NSICJwbG90dml6LkNoYXJ0XFxEZWZhdWx0SWNvbiIgIiIgIiRJTlNURElSXFxhc3NldHNcXHB2aXouaWNvIicsCiAgICAnICBXcml0ZVJlZ1N0ciBIS0NSICJwbG90dml6LkNoYXJ0XFxzaGVsbFxcb3BlblxcY29tbWFuZCIgIiIgXCIkSU5TVERJUlxccGxvdHZpei5leGVcIiBcIiUxXCInLAogICAgJycsCiAgICAnICBXcml0ZVJlZ1N0ciBIS0NSICIucHZpenQiICIiICJwbG90dml6LlRlbXBsYXRlIicsCiAgICAnICBXcml0ZVJlZ1N0ciBIS0NSICJwbG90dml6LlRlbXBsYXRlIiAiIiAicGxvdHZpeiBUZW1wbGF0ZSInLAogICAgJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5UZW1wbGF0ZVxcRGVmYXVsdEljb24iICIiICIkSU5TVERJUlxcYXNzZXRzXFxwdml6dC5pY28iJywKICAgICcgIFdyaXRlUmVnU3RyIEhLQ1IgInBsb3R2aXouVGVtcGxhdGVcXHNoZWxsXFxvcGVuXFxjb21tYW5kIiAiIiBcIiRJTlNURElSXFxwbG90dml6LmV4ZVwiIFwiJTFcIicsCiAgICAnJywKICAgICcgIFdyaXRlUmVnU3RyIEhLQ1IgIi5wdml6eCIgIiIgInBsb3R2aXouUGFsZXR0ZUJ1bmRsZSInLAogICAgJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5QYWxldHRlQnVuZGxlIiAiIiAicGxvdHZpeiBQYWxldHRlIEJ1bmRsZSInLAogICAgJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5QYWxldHRlQnVuZGxlXFxEZWZhdWx0SWNvbiIgIiIgIiRJTlNURElSXFxhc3NldHNcXHB2aXp4LmljbyInLAogICAgJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5QYWxldHRlQnVuZGxlXFxzaGVsbFxcb3BlblxcY29tbWFuZCIgIiIgXCIkSU5TVERJUlxccGxvdHZpei5leGVcIiBcIiUxXCInLAogICAgJycsCiAgICAnICBTeXN0ZW06OkNhbGwgInNoZWxsMzI6OlNIQ2hhbmdlTm90aWZ5KGkgMHg4MDAwMDAwLCBpIDAsIGkgMCwgaSAwKSInLAogICAgJ1NlY3Rpb25FbmQnLAogICAgJycsCiAgICAnU2VjdGlvbiAiVW5pbnN0YWxsIicsCiAgICAnICBEZWxldGUgIiRJTlNURElSXFxVbmluc3RhbGwuZXhlIicsCiAgICAnICBSTURpciAvciAiJElOU1RESVIiJywKICAgICcgIERlbGV0ZSAiJFNNUFJPR1JBTVNcXHBsb3R2aXpcXHBsb3R2aXoubG5rIicsCiAgICAnICBEZWxldGUgIiRTTVBST0dSQU1TXFxwbG90dml6XFxVbmluc3RhbGwubG5rIicsCiAgICAnICBSTURpciAiJFNNUFJPR1JBTVNcXHBsb3R2aXoiJywKICAgICcgIERlbGV0ZSAiJERFU0tUT1BcXHBsb3R2aXoubG5rIicsCiAgICAnICBEZWxldGVSZWdLZXkgSEtMTSAiU29mdHdhcmVcXE1pY3Jvc29mdFxcV2luZG93c1xcQ3VycmVudFZlcnNpb25cXFVuaW5zdGFsbFxccGxvdHZpeiInLAogICAgJyAgRGVsZXRlUmVnS2V5IEhLTE0gIlNvZnR3YXJlXFxwbG90dml6IicsCiAgICAnICBEZWxldGVSZWdLZXkgSEtDUiAiLnB2aXoiJywKICAgICcgIERlbGV0ZVJlZ0tleSBIS0NSICJwbG90dml6LkNoYXJ0IicsCiAgICAnICBEZWxldGVSZWdLZXkgSEtDUiAiLnB2aXp0IicsCiAgICAnICBEZWxldGVSZWdLZXkgSEtDUiAicGxvdHZpei5UZW1wbGF0ZSInLAogICAgJyAgRGVsZXRlUmVnS2V5IEhLQ1IgIi5wdml6eCInLAogICAgJyAgRGVsZXRlUmVnS2V5IEhLQ1IgInBsb3R2aXouUGFsZXR0ZUJ1bmRsZSInLAogICAgJyAgU3lzdGVtOjpDYWxsICJzaGVsbDMyOjpTSENoYW5nZU5vdGlmeShpIDB4ODAwMDAwMCwgaSAwLCBpIDAsIGkgMCkiJywKICAgICdTZWN0aW9uRW5kJywKXQoKbnNpLndyaXRlX3RleHQoIlxuIi5qb2luKGxpbmVzKSwgZW5jb2Rpbmc9InV0Zi04IikKcHJpbnQoZiIgIHtuc2l9IHdyaXR0ZW4iKQ==').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
where makensis >nul 2>&1
if errorlevel 1 (
    echo ^> makensis not found -- skipping installer.
    echo    Install NSIS from https://nsis.sourceforge.io to build a setup.exe
) else (
    echo ^> Building NSIS installer...
    cd "%DIST_DIR%"
    makensis installer.nsi
    cd "%ROOT_DIR%"
    if exist "%INSTALLER_OUT%" (
        echo    %INSTALLER_OUT% created.
    ) else (
        echo    WARNING: NSIS ran but installer not found.
    )
)

echo.
echo ^> Creating portable zip...
if exist "%ZIP_OUT%" del "%ZIP_OUT%"

where powershell >nul 2>&1
if errorlevel 1 (
    where 7z >nul 2>&1
    if errorlevel 1 (
        echo    WARNING: Neither PowerShell nor 7-Zip -- skipping zip.
    ) else (
        7z a -tzip "%ZIP_OUT%" ".\%APP_DIR%\*" >nul
        echo    %ZIP_OUT% created via 7-Zip.
    )
) else (
    powershell -NoProfile -Command "Compress-Archive -Path '%APP_DIR%\*' -DestinationPath '%ZIP_OUT%' -Force"
    echo    %ZIP_OUT% created via PowerShell.
)

echo.
echo ================================================
echo   Build succeeded
echo   EXE     : %EXE%
if exist "%INSTALLER_OUT%" echo   Installer: %INSTALLER_OUT%
if exist "%ZIP_OUT%"       echo   Portable : %ZIP_OUT%
echo.
echo   Test    : %EXE%
echo ================================================
