"""
Copyright (c) 2026 Paulo Cachim
ui/python_export.py  –  plotviz

PythonExportMixin: _export_python_bundle() / _export_to_code_runner().
Generates a .pvizx zip that contains:
  - plot.py        standalone matplotlib script (no plotviz dependency)
  - data/          one CSV per dataset used
  - README.md      quick-start instructions

The pure script-generation logic lives in core.script_gen (Qt-free, unit-tested).
This module is the thin Qt adapter that gathers UI state and drives file I/O.
generate_sns_plot_script() stays here because it reads widgets off the seaborn
explorer and is therefore UI-coupled.
"""

from __future__ import annotations
import io, os, zipfile
from PyQt6.QtWidgets import QFileDialog, QMessageBox

from core.script_gen import (
    generate_plot_script,
    _build_readme,
    _build_pyproject_toml,
)


def generate_sns_plot_script(explorer, chart_name: str, datasets: dict) -> str:
    """
    Build a complete standalone seaborn script for the given chart type,
    mirroring the current SeabornExplorer widget state.
    """

    def _esc(s):
        return str(s).replace('\\', '\\\\').replace("'", "\\'")

    def _col(combo):
        """Return (array, col_name) from a combo, or (None, '') if unset."""
        if combo is None:
            return None, ''
        txt = combo.currentText()
        if not txt or txt == '(none)' or txt not in datasets:
            return None, ''
        return datasets[txt], txt

    def _color():
        pal = explorer._sns_palette()
        return repr(pal[0]) if pal else "'steelblue'"

    lengths = {len(v) for v in datasets.values() if v is not None}
    use_combined = len(lengths) == 1

    # ── Header + imports ──────────────────────────────────────────────────────
    lines = [
        '#!/usr/bin/env python3',
        '"""',
        f'Auto-generated by plotviz Seaborn Explorer — {chart_name} chart.',
        '"""',
        '',
        'import os',
        'import numpy as np',
        'import pandas as pd',
        'import matplotlib.pyplot as plt',
        'import seaborn as sns',
        '',
        '# ── Data loading ─────────────────────────────────────────────────────',
        "_here = os.path.dirname(os.path.abspath(__file__))",
    ]

    if use_combined:
        lines += [
            "df = pd.read_csv(os.path.join(_here, 'data', 'data.csv'))",
        ]
    else:
        col_names = list(datasets.keys())
        for col in col_names:
            safe = ''.join(c if c.isalnum() or c in '-_.' else '_' for c in col)
            lines.append(
                f"_s_{safe} = pd.read_csv(os.path.join(_here, 'data', '{safe}.csv'))['{_esc(col)}']"
            )
        lines += [
            "df = pd.concat([" +
            ", ".join(
                f"_s_{''.join(c if c.isalnum() or c in '-_.' else '_' for c in col)}.rename('{_esc(col)}')"
                for col in col_names
            ) + "], axis=1)",
        ]

    lines += ['', '# ── Plot ─────────────────────────────────────────────────────']

    _, xn = _col(explorer._x_combo)
    _, yn = _col(explorer._y_combo)
    col   = _color()

    if chart_name == 'KDE':
        lines += [
            'fig, ax = plt.subplots()',
            f'sns.kdeplot(',
            f"    x=df['{_esc(yn)}'].astype(float), ax=ax,",
            f'    fill={explorer._kde_fill.isChecked()},',
            f'    alpha={explorer._kde_alpha.value()},',
            f'    linewidth={explorer._kde_lw.value()},',
            f'    bw_adjust={explorer._kde_bw.value()},',
            f'    cumulative={explorer._kde_cumul.isChecked()},',
            f'    common_norm={explorer._kde_common.isChecked()},',
            f'    color={col},',
            ')',
            f"ax.set_xlabel('{_esc(yn)}'); ax.set_ylabel('Density')",
        ]

    elif chart_name == 'Regression':
        lowess = explorer._reg_lowess.isChecked()
        robust = explorer._reg_robust.isChecked()
        order  = 1 if (lowess or robust) else explorer._reg_order.value()
        ci_val = None if (lowess or robust) else (explorer._reg_ci.value() or None)
        lines += [
            'fig, ax = plt.subplots()',
            'sns.regplot(',
            f"    x=df['{_esc(xn)}'].astype(float), y=df['{_esc(yn)}'].astype(float), ax=ax,",
            f'    scatter_kws={{"s": {explorer._reg_size.value()}, "alpha": {explorer._reg_alpha.value()}}},',
            f'    line_kws={{"linewidth": 1.8}},',
            f'    ci={repr(ci_val)},',
            f'    order={order}, robust={robust}, lowess={lowess},',
            f'    scatter={explorer._reg_scatter.isChecked()},',
            f'    color={col},',
            ')',
            f"ax.set_xlabel('{_esc(xn)}'); ax.set_ylabel('{_esc(yn)}')",
        ]

    elif chart_name == 'Strip':
        lines += [
            f"df['_x'] = df['{_esc(xn)}'].astype(str) if df['{_esc(xn)}'].dtype.kind not in 'biufc' else df['{_esc(xn)}'].copy()",
            'fig, ax = plt.subplots()',
            "sns.stripplot(data=df, x='_x', y='" + _esc(yn) + "', ax=ax,",
            f'    color={col},',
            f'    size={explorer._strip_size.value()},',
            f'    alpha={explorer._strip_alpha.value()},',
            f'    jitter={explorer._strip_jitter.value()},',
            ')',
            f"ax.set_xlabel('{_esc(xn)}'); ax.set_ylabel('{_esc(yn)}')",
        ]

    elif chart_name == 'Swarm':
        lines += [
            f"df['_x'] = df['{_esc(xn)}'].astype(str) if df['{_esc(xn)}'].dtype.kind not in 'biufc' else df['{_esc(xn)}'].copy()",
            'fig, ax = plt.subplots()',
            "sns.swarmplot(data=df, x='_x', y='" + _esc(yn) + "', ax=ax,",
            f'    color={col},',
            f'    size={explorer._swarm_size.value()},',
            f'    alpha={explorer._swarm_alpha.value()},',
            ')',
            f"ax.set_xlabel('{_esc(xn)}'); ax.set_ylabel('{_esc(yn)}')",
        ]

    elif chart_name == 'Heatmap':
        fmt = explorer._heat_fmt.currentText()
        num_cols = list(datasets.keys())
        lines += [
            f'_cols = {repr(num_cols)}',
            'corr = df[_cols].corr()',
            'fig, ax = plt.subplots(figsize=(max(6, len(_cols)), max(5, len(_cols))))',
            'sns.heatmap(corr, ax=ax,',
            f'    cmap={repr(explorer._heat_cmap.currentText())},',
            f'    annot={explorer._heat_annot.isChecked()},',
            f'    fmt={repr(fmt) if explorer._heat_annot.isChecked() else repr("")},',
            f'    linewidths={explorer._heat_lw.value()},',
            f'    square={explorer._heat_square.isChecked()},',
            f'    cbar={explorer._heat_cbar.isChecked()},',
            f'    robust={explorer._heat_robust.isChecked()},',
            ')',
            "ax.set_title('Correlation Heatmap', fontsize=11, pad=8)",
        ]

    elif chart_name == 'Pairplot':
        num_cols = list(datasets.keys())
        _pair_hue_name = explorer._hue_combo.currentText()
        _pair_hue = None if _pair_hue_name in ('', '(none)') else _pair_hue_name
        _pair_pal_name = explorer._sns_palette_name()
        _pair_pal = _pair_pal_name if _pair_pal_name else repr(explorer._sns_palette(len(num_cols)))
        _pair_hue_lines = []
        if _pair_hue and _pair_hue in datasets:
            _pair_hue_lines = [
                f"df[{repr(_pair_hue)}] = df[{repr(_pair_hue)}].astype(str)",
            ]
        lines += _pair_hue_lines + [
            f'_cols = {repr(num_cols)}',
            'pg = sns.pairplot(df[_cols' + (f' + [{repr(_pair_hue)}]' if _pair_hue else '') + '],',
            f'    hue={repr(_pair_hue)},',
            f'    diag_kind={repr(explorer._pair_diag.currentText())},',
            f'    kind={repr(explorer._pair_kind.currentText())},',
            f'    palette={repr(_pair_pal_name) if _pair_pal_name else _pair_pal},',
            f'    plot_kws={{"alpha": {explorer._pair_alpha.value()}}},',
            ')',
            'fig = pg.figure',
        ]

    elif chart_name == 'Joint':
        lines += [
            'jg = sns.jointplot(',
            f"    x=df['{_esc(xn)}'].astype(float), y=df['{_esc(yn)}'].astype(float),",
            f'    kind={repr(explorer._joint_kind.currentText())},',
            f'    ratio={explorer._joint_ratio.value()},',
            f'    marginal_kws={{"fill": {explorer._joint_margkde.isChecked()}}},',
            f'    alpha={explorer._joint_alpha.value()},',
            f'    color={col},',
            ')',
            f"jg.set_axis_labels('{_esc(xn)}', '{_esc(yn)}')",
            'fig = jg.figure',
        ]

    elif chart_name == 'Catplot':
        kind   = explorer._cat_kind.currentText()
        ci_str = explorer._cat_ci.currentText()
        if ci_str in ('95', '99'):
            eb = f"('ci', {ci_str})"
        elif ci_str == 'sd':
            eb = "'sd'"
        else:
            eb = 'None'
        _cat_pal_name = explorer._sns_palette_name()
        _cat_pal_line = (
            f'    palette={repr(_cat_pal_name)},'
            if _cat_pal_name else
            f'    palette={repr(explorer._sns_palette(10))},'
        )
        lines += [
            f"df['_x'] = df['{_esc(xn)}'].astype(str)",
            "fg = sns.catplot(",
            f"    data=df, x='_x', y='{_esc(yn)}',",
            f'    kind={repr(kind)},',
            _cat_pal_line,
            f'    alpha={explorer._cat_alpha.value()},',
            f'    saturation={explorer._cat_sat.value()},',
        ]
        if kind in ('bar', 'point'):
            lines.append(f'    errorbar={eb},')
        lines += [
            ')',
            f"fg.set_axis_labels('{_esc(xn)}', '{_esc(yn)}')",
            'fig = fg.figure',
        ]

    else:
        lines += ['fig, ax = plt.subplots()', "ax.set_title('No chart type matched')"]

    lines += ['', 'plt.tight_layout()', 'plt.show()', '']
    return '\n'.join(lines)





class PythonExportMixin:
    """Mixin that adds _export_python_bundle() to PlotVizApp."""

    def _export_python_bundle(self):
        """Export a .pvizx zip: plot.py + data CSVs + README."""
        import csv as _csv
        import numpy as np

        # ── Collect state ──────────────────────────────────────────────────────
        settings    = self._collect_settings()
        # Annotations (text / arrow / image) are not part of _collect_settings();
        # add them so the generated script can reproduce them.
        settings['annotations'] = self._collect_annotations_meta()
        series_meta = self._collect_series_meta()
        series_list = series_meta.get('series', [])

        # Determine which columns are used
        used_cols: set[str] = set()
        for s in series_list:
            for k in ('x_col', 'y_col'):
                c = s.get(k, '')
                if c and c in self.datasets:
                    used_cols.add(c)
        for attr in ('combo_z', 'combo_err', 'combo_bar_ymin'):
            cb = getattr(self, attr, None)
            if cb:
                txt = cb.currentText()
                if txt and txt != '(none)' and txt in self.datasets:
                    used_cols.add(txt)
        # U/V columns for quiver, barbs, and streamplot live in series_meta,
        # not in the series rows — add them so they are written to the CSV.
        for _uv_key in ('quiver_u_col', 'quiver_v_col',
                        'barbs_u_col',  'barbs_v_col',
                        'stream_u_col', 'stream_v_col'):
            c = series_meta.get(_uv_key, '')
            if c and c != '(none)' and c in self.datasets:
                used_cols.add(c)
        # Fall back to all columns if nothing is explicitly assigned
        export_cols = used_cols if used_cols else set(self.datasets.keys())
        datasets_to_export = {k: self.datasets[k] for k in export_cols if k in self.datasets}

        # ── Palette ────────────────────────────────────────────────────────────
        palette = [self._palette_color(i) for i in range(16)]

        # ── Chart title for filename ───────────────────────────────────────────
        chart_title = (settings.get('title_text') or
                       getattr(self, '_current_filepath', None) and
                       os.path.splitext(os.path.basename(self._current_filepath))[0] or
                       'chart')

        # ── File dialog ────────────────────────────────────────────────────────
        from ui.helpers import _get_dir, _remember_dir
        _stem = (os.path.splitext(os.path.basename(self._current_filepath))[0]
                 if getattr(self, '_current_filepath', None) else chart_title or 'untitled')
        fp, _ = QFileDialog.getSaveFileName(
            self, 'Export Python Bundle', os.path.join(_get_dir(), _stem + '.pvizx'),
            'plotviz Python Bundle (*.pvizx);;All Files (*)')
        if not fp:
            return
        _remember_dir(fp)
        if not fp.endswith('.pvizx'):
            fp += '.pvizx'

        try:
            # ── Generate script ────────────────────────────────────────────────
            n_subplots = settings.get('subplot_rows', 1) * settings.get('subplot_cols', 1)
            script = generate_plot_script(
                settings, series_meta, datasets_to_export, palette, chart_title)

            # ── Build CSVs ─────────────────────────────────────────────────────
            lengths   = {len(v) for v in datasets_to_export.values() if v is not None}
            use_combined = len(lengths) == 1

            with zipfile.ZipFile(fp, 'w', zipfile.ZIP_DEFLATED) as zf:
                zf.writestr('plot.py', script)
                zf.writestr('README.md', _build_readme(chart_title, datasets_to_export, n_subplots))
                zf.writestr('pyproject.toml', _build_pyproject_toml(chart_title, script))

                # Embed any image-annotation files referenced by the script
                # (script loads them from images/<basename> relative to plot.py).
                for _ann in self.canvas.annotations:
                    if _ann.get('type') != 'image':
                        continue
                    _src = _ann.get('filepath', '')
                    if _src and os.path.isfile(_src):
                        try:
                            zf.write(_src, 'images/' + os.path.basename(_src))
                        except Exception:
                            pass

                if use_combined:
                    # Single CSV with all columns
                    buf = io.StringIO()
                    writer = _csv.writer(buf)
                    col_names = list(datasets_to_export.keys())
                    writer.writerow(col_names)
                    n_rows = len(next(iter(datasets_to_export.values())))
                    for row_idx in range(n_rows):
                        writer.writerow([
                            datasets_to_export[c][row_idx]
                            if row_idx < len(datasets_to_export[c]) else ''
                            for c in col_names
                        ])
                    zf.writestr('data/data.csv', buf.getvalue())
                else:
                    # One CSV per column
                    for col_name, arr in datasets_to_export.items():
                        buf = io.StringIO()
                        writer = _csv.writer(buf)
                        writer.writerow([col_name])
                        for v in arr:
                            writer.writerow([v])
                        # Sanitise filename
                        safe = ''.join(c if c.isalnum() or c in '-_.' else '_' for c in col_name)
                        zf.writestr(f'data/{safe}.csv', buf.getvalue())

            QMessageBox.information(self, 'Exported',
                f'Python bundle saved to:\n{fp}\n\n'
                f'Extract the zip and run: python plot.py')

        except Exception as e:
            import traceback as _tb
            QMessageBox.critical(self, 'Export error', f'{e}\n\n{_tb.format_exc()}')

    def _export_to_code_runner(self):
        """Build a .pvizx bundle from the current chart and open it directly in Code Runner.

        Unlike _export_python_bundle(), this method skips the Save dialog and
        writes the bundle to a temporary file, then hands it off to the Code
        Runner so the user can inspect and tweak the generated script immediately.
        """
        import csv as _csv
        import tempfile
        import numpy as np

        # ── Collect state ──────────────────────────────────────────────────────
        settings    = self._collect_settings()
        # Annotations are not part of _collect_settings(); add them so the
        # generated script reproduces them in the Code Runner.
        settings['annotations'] = self._collect_annotations_meta()
        series_meta = self._collect_series_meta()
        series_list = series_meta.get('series', [])

        # Determine which columns are used (mirrors _export_python_bundle logic)
        used_cols: set[str] = set()
        for s in series_list:
            for k in ('x_col', 'y_col'):
                c = s.get(k, '')
                if c and c in self.datasets:
                    used_cols.add(c)
        for attr in ('combo_z', 'combo_err', 'combo_bar_ymin'):
            cb = getattr(self, attr, None)
            if cb:
                txt = cb.currentText()
                if txt and txt != '(none)' and txt in self.datasets:
                    used_cols.add(txt)
        # U/V columns for quiver, barbs, and streamplot live in series_meta,
        # not in the series rows — add them so they are written to the CSV.
        for _uv_key in ('quiver_u_col', 'quiver_v_col',
                        'barbs_u_col',  'barbs_v_col',
                        'stream_u_col', 'stream_v_col'):
            c = series_meta.get(_uv_key, '')
            if c and c != '(none)' and c in self.datasets:
                used_cols.add(c)
        export_cols = used_cols if used_cols else set(self.datasets.keys())
        datasets_to_export = {k: self.datasets[k] for k in export_cols if k in self.datasets}

        if not datasets_to_export:
            QMessageBox.warning(self, 'No data',
                'No datasets are loaded — cannot open in Code Runner.')
            return

        # ── Palette & title ────────────────────────────────────────────────────
        palette = [self._palette_color(i) for i in range(16)]
        chart_title = (settings.get('title_text') or
                       getattr(self, '_current_filepath', None) and
                       os.path.splitext(os.path.basename(self._current_filepath))[0] or
                       'chart')

        try:
            # ── Generate script ────────────────────────────────────────────────
            n_subplots = settings.get('subplot_rows', 1) * settings.get('subplot_cols', 1)
            script = generate_plot_script(
                settings, series_meta, datasets_to_export, palette, chart_title)

            # ── Build CSVs ─────────────────────────────────────────────────────
            lengths      = {len(v) for v in datasets_to_export.values() if v is not None}
            use_combined = len(lengths) == 1

            # Write to a named temp file that persists until the Code Runner
            # extracts and runs it (Code Runner manages its own cleanup via
            # _pvizx_tmpdir, so we only need to ensure the zip itself survives
            # long enough to be read by load_pvizx).
            tmp_fd, tmp_fp = tempfile.mkstemp(suffix='.pvizx', prefix='plotviz_cr_')
            os.close(tmp_fd)

            with zipfile.ZipFile(tmp_fp, 'w', zipfile.ZIP_DEFLATED) as zf:
                zf.writestr('plot.py', script)
                zf.writestr('README.md', _build_readme(chart_title, datasets_to_export, n_subplots))
                zf.writestr('pyproject.toml', _build_pyproject_toml(chart_title, script))

                # Embed any image-annotation files referenced by the script.
                for _ann in self.canvas.annotations:
                    if _ann.get('type') != 'image':
                        continue
                    _src = _ann.get('filepath', '')
                    if _src and os.path.isfile(_src):
                        try:
                            zf.write(_src, 'images/' + os.path.basename(_src))
                        except Exception:
                            pass

                if use_combined:
                    buf = io.StringIO()
                    writer = _csv.writer(buf)
                    col_names = list(datasets_to_export.keys())
                    writer.writerow(col_names)
                    n_rows = len(next(iter(datasets_to_export.values())))
                    for row_idx in range(n_rows):
                        writer.writerow([
                            datasets_to_export[c][row_idx]
                            if row_idx < len(datasets_to_export[c]) else ''
                            for c in col_names
                        ])
                    zf.writestr('data/data.csv', buf.getvalue())
                else:
                    for col_name, arr in datasets_to_export.items():
                        buf = io.StringIO()
                        writer = _csv.writer(buf)
                        writer.writerow([col_name])
                        for v in arr:
                            writer.writerow([v])
                        safe = ''.join(c if c.isalnum() or c in '-_.' else '_' for c in col_name)
                        zf.writestr(f'data/{safe}.csv', buf.getvalue())

            # ── Hand off to Code Runner ────────────────────────────────────────
            self._open_pvizx_in_code_runner(tmp_fp)

        except Exception as e:
            import traceback as _tb
            QMessageBox.critical(self, 'Code Runner export error', f'{e}\n\n{_tb.format_exc()}')
