@echo off
setlocal enabledelayedexpansion

:: -- plotviz Windows package builder ------------------------------------------
:: Produces:
::   dist\plotviz\           -- one-folder app (PyInstaller)
::   dist\plotviz-VERSION-setup.exe  -- NSIS installer (if makensis on PATH)
::   dist\plotviz-VERSION-win.zip    -- portable zip   (always)
::
:: Requirements:
::   uv      https://astral.sh/uv
::   NSIS    https://nsis.sourceforge.io  (optional)
::
:: Usage (from repo root):
::   create_pkg_win.bat
:: -----------------------------------------------------------------------------

set "ROOT_DIR=%~dp0"
set "ROOT_DIR=%ROOT_DIR:~0,-1%"
cd /d "%ROOT_DIR%"

echo.
echo ================================================
echo    plotviz Windows package builder
echo    Root : %ROOT_DIR%
echo ================================================

where uv >nul 2>&1
if errorlevel 1 (
    echo [ERROR] uv not found.
    echo         Install: winget install astral-sh.uv
    exit /b 1
)

for /f "tokens=*" %%v in ('uv --version') do set UV_VER=%%v
for /f "tokens=*" %%v in ('uv run python --version') do set PY_VER=%%v
echo    uv     : %UV_VER%
echo    Python : %PY_VER%

for /f "tokens=*" %%v in ('uv run python -c "import pathlib;t=pathlib.Path('src/plotviz/config/_version.py').read_text();print([l.split(chr(34))[1] for l in t.splitlines() if l.startswith('__version__')][0])"') do set VERSION=%%v
echo    Version: %VERSION%

set "APP_NAME=plotviz"
set "SPEC_FILE=plotviz_win.spec"
set "DIST_DIR=dist"
set "ASSETS_DIR=assets"
set "ICON_ICO=%ASSETS_DIR%\plotviz.ico"
set "APP_DIR=%DIST_DIR%\%APP_NAME%"
set "EXE=%APP_DIR%\%APP_NAME%.exe"
set "ZIP_OUT=%DIST_DIR%\%APP_NAME%-%VERSION%-win.zip"
set "INSTALLER_OUT=%DIST_DIR%\%APP_NAME%-%VERSION%-setup.exe"
set "NSIS_SCRIPT=%DIST_DIR%\installer.nsi"

echo.
echo ^> Syncing dependencies...
uv sync
if errorlevel 1 ( echo [ERROR] uv sync failed & exit /b 1 )

for /f "tokens=*" %%v in ('uv run pyinstaller --version') do set PI_VER=%%v
echo.
echo ^> PyInstaller %PI_VER%

echo.
echo ^> Converting app icon to .ico...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('ZnJvbSBQSUwgaW1wb3J0IEltYWdlCmltcG9ydCBpbywgc3RydWN0LCBwYXRobGliLCBzeXMKCmljbnMgPSBwYXRobGliLlBhdGgoImFzc2V0cy9wbG90dml6LmljbnMiKQppY28gID0gcGF0aGxpYi5QYXRoKCJhc3NldHMvcGxvdHZpei5pY28iKQoKaWYgbm90IGljbnMuZXhpc3RzKCk6CiAgICBwcmludCgiICBXQVJOSU5HOiBwbG90dml6LmljbnMgbm90IGZvdW5kIC0tIHNraXBwaW5nIC5pY28gY29udmVyc2lvbiIpCiAgICBzeXMuZXhpdCgwKQoKZGF0YSA9IGljbnMucmVhZF9ieXRlcygpCnBvcyA9IDgKYmVzdCwgYmVzdF9weCA9IE5vbmUsIDAKd2hpbGUgcG9zIDwgbGVuKGRhdGEpOgogICAgc2l6ZSA9IHN0cnVjdC51bnBhY2soIj5JIiwgZGF0YVtwb3MrNDpwb3MrOF0pWzBdCiAgICBwYXlsb2FkID0gZGF0YVtwb3MrODpwb3Mrc2l6ZV0KICAgIGlmIHBheWxvYWRbOjhdID09IGIiXHg4OVBOR1xyXG5ceDFhXG4iOgogICAgICAgIGltZyA9IEltYWdlLm9wZW4oaW8uQnl0ZXNJTyhwYXlsb2FkKSkKICAgICAgICBpZiBpbWcuc2l6ZVswXSAqIGltZy5zaXplWzFdID4gYmVzdF9weDoKICAgICAgICAgICAgYmVzdCwgYmVzdF9weCA9IHBheWxvYWQsIGltZy5zaXplWzBdICogaW1nLnNpemVbMV0KICAgIHBvcyArPSBzaXplCgppZiBiZXN0IGlzIE5vbmU6CiAgICBwcmludCgiICBXQVJOSU5HOiBubyBQTkcgZm91bmQgaW4gLmljbnMgLS0gc2tpcHBpbmcgLmljbyBjb252ZXJzaW9uIikKICAgIHN5cy5leGl0KDApCgpzcmMgPSBJbWFnZS5vcGVuKGlvLkJ5dGVzSU8oYmVzdCkpLmNvbnZlcnQoIlJHQkEiKQpzaXplcyA9IFsxNiwgMzIsIDQ4LCA2NCwgMTI4LCAyNTZdCmltZ3MgID0gW3NyYy5yZXNpemUoKHMsIHMpLCBJbWFnZS5MQU5DWk9TKSBmb3IgcyBpbiBzaXplc10KaW1nc1swXS5zYXZlKHN0cihpY28pLCBmb3JtYXQ9IklDTyIsIHNpemVzPVsocywgcykgZm9yIHMgaW4gc2l6ZXNdLAogICAgICAgICAgICAgYXBwZW5kX2ltYWdlcz1pbWdzWzE6XSkKcHJpbnQoZiIgIHBsb3R2aXouaWNvIHdyaXR0ZW4gKHtsZW4oc2l6ZXMpfSBzaXplcykiKQ==').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
echo ^> Generating file-type icons (.ico)...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('ZnJvbSBQSUwgaW1wb3J0IEltYWdlLCBJbWFnZURyYXcsIEltYWdlRm9udAppbXBvcnQgaW8sIHN0cnVjdCwgcGF0aGxpYiwgc3lzCgpkZWYgZXh0cmFjdF9iYXNlKGljbnNfcGF0aCk6CiAgICBkYXRhID0gaWNuc19wYXRoLnJlYWRfYnl0ZXMoKQogICAgcG9zLCBiZXN0LCBiZXN0X3B4ID0gOCwgTm9uZSwgMAogICAgd2hpbGUgcG9zIDwgbGVuKGRhdGEpOgogICAgICAgIHNpemUgPSBzdHJ1Y3QudW5wYWNrKCI+SSIsIGRhdGFbcG9zKzQ6cG9zKzhdKVswXQogICAgICAgIHBheWxvYWQgPSBkYXRhW3Bvcys4OnBvcytzaXplXQogICAgICAgIGlmIHBheWxvYWRbOjhdID09IGIiXHg4OVBOR1xyXG5ceDFhXG4iOgogICAgICAgICAgICBpbWcgPSBJbWFnZS5vcGVuKGlvLkJ5dGVzSU8ocGF5bG9hZCkpCiAgICAgICAgICAgIGlmIGltZy5zaXplWzBdKmltZy5zaXplWzFdID4gYmVzdF9weDoKICAgICAgICAgICAgICAgIGJlc3QsIGJlc3RfcHggPSBwYXlsb2FkLCBpbWcuc2l6ZVswXSppbWcuc2l6ZVsxXQogICAgICAgIHBvcyArPSBzaXplCiAgICByZXR1cm4gSW1hZ2Uub3Blbihpby5CeXRlc0lPKGJlc3QpKS5jb252ZXJ0KCJSR0JBIikgaWYgYmVzdCBlbHNlIE5vbmUKCmRlZiBtYWtlX2RvY19pY29uKGJhc2UsIGJhbm5lcl9yZ2IsIGxhYmVsKToKICAgIFMgPSAyNTYKICAgIGltZyAgPSBJbWFnZS5uZXcoIlJHQkEiLCAoUywgUyksICgwLDAsMCwwKSkKICAgIGRyYXcgPSBJbWFnZURyYXcuRHJhdyhpbWcpCiAgICBSLCBGT0xELCBCQU5ORVJfSCA9IDE2LCAzNiwgNDAKICAgIHBsLHByLHB0LHBiID0gOCwgUy04LCA2LCBTLTYKICAgIGRyYXcucm91bmRlZF9yZWN0YW5nbGUoW3BsLHB0LHByLHBiXSwgcmFkaXVzPVIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBmaWxsPSgyNTUsMjU1LDI1NSwyNTUpLCBvdXRsaW5lPSgyMDAsMjAwLDIxMCwyNTUpLCB3aWR0aD0yKQogICAgZngsIGZ5ID0gcHItRk9MRCwgcHQrRk9MRAogICAgZHJhdy5wb2x5Z29uKFsoZngscHQpLChwcixwdCksKHByLGZ5KV0sIGZpbGw9KDAsMCwwLDApKQogICAgZHJhdy5wb2x5Z29uKFsoZngscHQpLChwcixmeSksKGZ4LGZ5KV0sIGZpbGw9KDIxOCwyMTgsMjMyLDI1NSkpCiAgICBkcmF3LmxpbmUoWyhmeCxwdCksKGZ4LGZ5KSwocHIsZnkpXSwgZmlsbD0oMTc1LDE3NSwyMDAsMjU1KSwgd2lkdGg9MikKICAgIGRyYXcubGluZShbKGZ4LHB0KSwocHIsZnkpXSwgZmlsbD0oMjAwLDIwMCwyMTUsMjU1KSwgd2lkdGg9MikKICAgIGFydCA9IGJhc2UuY29weSgpOyBhcnQudGh1bWJuYWlsKChmeC1wbC0xMiwgcGItQkFOTkVSX0gtcHQtMTIpLCBJbWFnZS5MQU5DWk9TKQogICAgY3ggPSBwbCs2KyhmeC1wbC0xMi1hcnQud2lkdGgpLy8yOyBjeSA9IHB0KzYrKHBiLUJBTk5FUl9ILXB0LTEyLWFydC5oZWlnaHQpLy8yCiAgICBpbWcuYWxwaGFfY29tcG9zaXRlKGFydCwgKGN4LGN5KSkKICAgIGRyYXcgPSBJbWFnZURyYXcuRHJhdyhpbWcpCiAgICBwYWdlX21hc2sgPSBJbWFnZS5uZXcoIlJHQkEiLChTLFMpLCgwLDAsMCwwKSkKICAgIEltYWdlRHJhdy5EcmF3KHBhZ2VfbWFzaykucm91bmRlZF9yZWN0YW5nbGUoW3BsLHB0LHByLHBiXSxyYWRpdXM9UixmaWxsPSgyNTUsMjU1LDI1NSwyNTUpKQogICAgYmFubmVyID0gSW1hZ2UubmV3KCJSR0JBIiwoUyxTKSwoMCwwLDAsMCkpCiAgICBJbWFnZURyYXcuRHJhdyhiYW5uZXIpLnJlY3RhbmdsZShbcGwscGItQkFOTkVSX0gscHIscGJdLGZpbGw9KCpiYW5uZXJfcmdiLDI1NSkpCiAgICBjbGlwcGVkID0gSW1hZ2UubmV3KCJSR0JBIiwoUyxTKSwoMCwwLDAsMCkpCiAgICBjbGlwcGVkLnBhc3RlKGJhbm5lciwgbWFzaz1wYWdlX21hc2suc3BsaXQoKVszXSkKICAgIGltZyA9IEltYWdlLmFscGhhX2NvbXBvc2l0ZShpbWcsIGNsaXBwZWQpCiAgICBkcmF3ID0gSW1hZ2VEcmF3LkRyYXcoaW1nKQogICAgdHJ5OgogICAgICAgIGZvbnQgPSBJbWFnZUZvbnQudHJ1ZXR5cGUoIkM6L1dpbmRvd3MvRm9udHMvYXJpYWxiZC50dGYiLCAyMikKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgZm9udCA9IEltYWdlRm9udC5sb2FkX2RlZmF1bHQoKQogICAgYmIgPSBkcmF3LnRleHRiYm94KCgwLDApLCBsYWJlbCwgZm9udD1mb250KQogICAgdHcsdGggPSBiYlsyXS1iYlswXSwgYmJbM10tYmJbMV0KICAgIHR4ID0gKHBsK3ByKS8vMiAtIHR3Ly8yCiAgICB0eSA9IHBiLUJBTk5FUl9IICsgKEJBTk5FUl9ILXRoKS8vMiAtIGJiWzFdCiAgICBkcmF3LnRleHQoKHR4LHR5KSwgbGFiZWwsIGZvbnQ9Zm9udCwgZmlsbD0oMjU1LDI1NSwyNTUsMjU1KSkKICAgIHJldHVybiBpbWcKCmljbnMgPSBwYXRobGliLlBhdGgoImFzc2V0cy9wbG90dml6LmljbnMiKQppZiBub3QgaWNucy5leGlzdHMoKToKICAgIHByaW50KCIgIFdBUk5JTkc6IHBsb3R2aXouaWNucyBub3QgZm91bmQgLS0gc2tpcHBpbmcgZmlsZS10eXBlIGljb25zIikKICAgIHN5cy5leGl0KDApCgpiYXNlID0gZXh0cmFjdF9iYXNlKGljbnMpCmlmIGJhc2UgaXMgTm9uZToKICAgIHByaW50KCIgIFdBUk5JTkc6IGNvdWxkIG5vdCBleHRyYWN0IGJhc2UgYXJ0IC0tIHNraXBwaW5nIik7IHN5cy5leGl0KDApCgpUWVBFUyA9IFsKICAgICgicHZpeiIsICAoIDUyLDEyMCwyMjApLCAiLnB2aXoiKSwKICAgICgicHZpenQiLCAoMjEwLDEzMCwgMjApLCAiLnB2aXp0IiksCiAgICAoInB2aXpjIiwgKCAyMCwxNjAsMTYwKSwgIi5wdml6YyIpLAogICAgKCJwdml6cCIsICgxNDAsIDYwLDIwMCksICIucHZpenAiKSwKXQppY29fc2l6ZXMgPSBbMTYsMzIsNDgsNjQsMTI4LDI1Nl0KZm9yIHN0ZW0sIHJnYiwgbGFiZWwgaW4gVFlQRVM6CiAgICBpY29uMjU2ID0gbWFrZV9kb2NfaWNvbihiYXNlLCByZ2IsIGxhYmVsKQogICAgaW1ncyA9IFtpY29uMjU2LnJlc2l6ZSgocyxzKSwgSW1hZ2UuTEFOQ1pPUykgZm9yIHMgaW4gaWNvX3NpemVzXQogICAgb3V0ID0gcGF0aGxpYi5QYXRoKGYiYXNzZXRzL3tzdGVtfS5pY28iKQogICAgaW1nc1swXS5zYXZlKHN0cihvdXQpLCBmb3JtYXQ9IklDTyIsIHNpemVzPVsocyxzKSBmb3IgcyBpbiBpY29fc2l6ZXNdLAogICAgICAgICAgICAgICAgIGFwcGVuZF9pbWFnZXM9aW1nc1sxOl0pCiAgICBwcmludChmIiAge291dH0gd3JpdHRlbiIp').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
echo ^> Writing %SPEC_FILE%...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('aW1wb3J0IHBhdGhsaWIsIHRleHR3cmFwCgpST09UID0gcGF0aGxpYi5QYXRoKCIuIikKCnNwZWMgPSAiIiIjIC0qLSBtb2RlOiBweXRob24gOyBjb2Rpbmc6IHV0Zi04IC0qLQojIHBsb3R2aXpfd2luLnNwZWMgLS0gUHlJbnN0YWxsZXIgc3BlYyBmb3IgV2luZG93cwojIEF1dG8tZ2VuZXJhdGVkIGJ5IGNyZWF0ZV9wa2dfd2luLmJhdCAtLSBkbyBub3QgZWRpdCBieSBoYW5kLgoKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCmZyb20gUHlJbnN0YWxsZXIudXRpbHMuaG9va3MgaW1wb3J0IGNvbGxlY3RfZGF0YV9maWxlcywgY29sbGVjdF9zdWJtb2R1bGVzCmltcG9ydCBpbXBvcnRsaWIudXRpbCBhcyBfaWx1CgpfdnNwZWMgPSBQYXRoKFNQRUNQQVRIKSAvICJzcmMiIC8gInBsb3R2aXoiIC8gImNvbmZpZyIgLyAiX3ZlcnNpb24ucHkiCl92bW9kICA9IF9pbHUuc3BlY19mcm9tX2ZpbGVfbG9jYXRpb24oIl92ZXJzaW9uIiwgX3ZzcGVjKQpfdm0gICAgPSBfaWx1Lm1vZHVsZV9mcm9tX3NwZWMoX3Ztb2QpOyBfdm1vZC5sb2FkZXIuZXhlY19tb2R1bGUoX3ZtKQpBUFBfVkVSU0lPTiA9IF92bS5fX3ZlcnNpb25fXwoKUk9PVF9ESVIgPSBQYXRoKFNQRUNQQVRIKQpQS0dfRElSICA9IFJPT1RfRElSIC8gInNyYyIgLyAicGxvdHZpeiIKCmhpZGRlbl9pbXBvcnRzID0gWwogICAgIlB5UXQ2IiwgIlB5UXQ2LlF0V2lkZ2V0cyIsICJQeVF0Ni5RdENvcmUiLCAiUHlRdDYuUXRHdWkiLAogICAgIlB5UXQ2LlF0UHJpbnRTdXBwb3J0IiwgIlB5UXQ2LnNpcCIsCiAgICAibWF0cGxvdGxpYiIsICJtYXRwbG90bGliLnB5cGxvdCIsCiAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX3F0NWFnZyIsCiAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX3F0YWdnIiwKICAgICJtYXRwbG90bGliLmJhY2tlbmRzLmJhY2tlbmRfYWdnIiwKICAgICJtYXRwbG90bGliLmJhY2tlbmRzLmJhY2tlbmRfc3ZnIiwKICAgICJtYXRwbG90bGliLmJhY2tlbmRzLmJhY2tlbmRfcGRmIiwKICAgICJtYXRwbG90bGliLmZpZ3VyZSIsICJtYXRwbG90bGliLnRpY2tlciIsICJtYXRwbG90bGliLmNvbG9ycyIsCiAgICAibWF0cGxvdGxpYi5jbSIsICJtYXRwbG90bGliLnBhdGNoZXMiLCAibWF0cGxvdGxpYi5saW5lcyIsCiAgICAibWF0cGxvdGxpYi5jb2xsZWN0aW9ucyIsICJtYXRwbG90bGliLmNvbnRvdXIiLCAibWF0cGxvdGxpYi5pbWFnZSIsCiAgICAibWF0cGxvdGxpYi5heGVzLl9heGVzIiwgIm1hdHBsb3RsaWIuYXhlcy5fYmFzZSIsCiAgICAibWF0cGxvdGxpYi5heGVzLl9zZWNvbmRhcnlfYXhlcyIsCiAgICAibXBsX3Rvb2xraXRzIiwgIm1wbF90b29sa2l0cy5tcGxvdDNkIiwKICAgICJtcGxfdG9vbGtpdHMubXBsb3QzZC5heGVzM2QiLCAibXBsX3Rvb2xraXRzLm1wbG90M2QuYXJ0M2QiLAogICAgIm51bXB5IiwgIm51bXB5LmNvcmUuX211bHRpYXJyYXlfdW1hdGgiLCAibnVtcHkuY29yZS5tdWx0aWFycmF5IiwKICAgICJudW1weS5yYW5kb20iLCAibnVtcHkuZmZ0IiwgIm51bXB5LmxpbmFsZyIsCiAgICAic2NpcHkiLCAic2NpcHkub3B0aW1pemUiLCAic2NpcHkuc3RhdHMiLCAic2NpcHkuaW50ZXJwb2xhdGUiLAogICAgInNjaXB5LnNwZWNpYWwiLCAic2NpcHkubGluYWxnIiwKICAgICJzY2lweS5fbGliLm1lc3NhZ2VzdHJlYW0iLCAic2NpcHkuX2xpYi5fdXRpbCIsCiAgICAicGFuZGFzIiwKICAgICJwYW5kYXMuX2xpYnMudHNsaWJzLm5wX2RhdGV0aW1lIiwgInBhbmRhcy5fbGlicy50c2xpYnMubmF0dHlwZSIsCiAgICAicGFuZGFzLl9saWJzLnRzbGlicy50aW1lZGVsdGFzIiwgInBhbmRhcy5fbGlicy50c2xpYnMudGltZXN0YW1wcyIsCiAgICAicGFuZGFzLl9saWJzLnRzbGlicy5vZmZzZXRzIiwgInBhbmRhcy5fbGlicy50c2xpYnMucGVyaW9kIiwKICAgICJwYW5kYXMuX2xpYnMudHNsaWJzLnRpbWV6b25lcyIsICJwYW5kYXMuX2xpYnMubWlzc2luZyIsCiAgICAicGFuZGFzLmlvLmZvcm1hdHMuc3R5bGUiLCAicGFuZGFzLmlvLmV4Y2VsLl9vcGVucHl4bCIsCiAgICAib3BlbnB5eGwiLCAib3BlbnB5eGwuY2VsbC5fd3JpdGVyIiwgIm9wZW5weXhsLnN0eWxlcyIsCiAgICAib3BlbnB5eGwucmVhZGVyLmV4Y2VsIiwgIm9wZW5weXhsLndyaXRlci5leGNlbCIsCiAgICAib3BlbnB5eGwudXRpbHMiLCAib3BlbnB5eGwudXRpbHMuZGF0YWZyYW1lIiwKICAgICJ1aSIsICJ1aS5tYWluX3dpbmRvdyIsICJ1aS50YWJfYnVpbGRlcnMiLCAidWkucGxvdF9lbmdpbmUiLAogICAgInVpLnNlcmlhbGl6YXRpb24iLCAidWkuY2FudmFzIiwKICAgICJkYXRhIiwgImRhdGEubG9hZGVyIiwgImRhdGEuc2NpZW50aWZpYyIsCiAgICAic3R5bGluZyIsICJzdHlsaW5nLnByZXNldHMiLAogICAgImNvbmZpZyIsICJjb25maWcuc2V0dGluZ3MiLCAiY29uZmlnLl92ZXJzaW9uIiwKICAgICJ6aXBmaWxlIiwgImpzb24iLCAidGVtcGZpbGUiLCAidHJhY2ViYWNrIiwKICAgICJtdWx0aXByb2Nlc3NpbmciLCAibXVsdGlwcm9jZXNzaW5nLnBvb2wiLAogICAgIndpbnJlZyIsCl0KCmhpZGRlbl9pbXBvcnRzICs9IGNvbGxlY3Rfc3VibW9kdWxlcygibWF0cGxvdGxpYiIpCmhpZGRlbl9pbXBvcnRzICs9IGNvbGxlY3Rfc3VibW9kdWxlcygibXBsX3Rvb2xraXRzIikKaGlkZGVuX2ltcG9ydHMgKz0gY29sbGVjdF9zdWJtb2R1bGVzKCJzY2lweSIpCmhpZGRlbl9pbXBvcnRzICs9IGNvbGxlY3Rfc3VibW9kdWxlcygicGFuZGFzIikKaGlkZGVuX2ltcG9ydHMgKz0gY29sbGVjdF9zdWJtb2R1bGVzKCJvcGVucHl4bCIpCmhpZGRlbl9pbXBvcnRzICs9IGNvbGxlY3Rfc3VibW9kdWxlcygiUHlRdDYiKQoKZGF0YXMgPSBbXQpfYXNzZXRzID0gUk9PVF9ESVIgLyAiYXNzZXRzIgppZiBfYXNzZXRzLmV4aXN0cygpOgogICAgZGF0YXMgKz0gWyhzdHIoX2Fzc2V0cyksICJhc3NldHMiKV0KZGF0YXMgKz0gY29sbGVjdF9kYXRhX2ZpbGVzKCJtYXRwbG90bGliIikKZGF0YXMgKz0gY29sbGVjdF9kYXRhX2ZpbGVzKCJtcGxfdG9vbGtpdHMiKQpkYXRhcyArPSBjb2xsZWN0X2RhdGFfZmlsZXMoInBhbmRhcyIpCmRhdGFzICs9IGNvbGxlY3RfZGF0YV9maWxlcygib3BlbnB5eGwiKQpkYXRhcyArPSBjb2xsZWN0X2RhdGFfZmlsZXMoInNjaXB5IikKCl9pY28gPSBST09UX0RJUiAvICJhc3NldHMiIC8gInBsb3R2aXouaWNvIgpfaWNvbl9hcmcgPSBzdHIoX2ljbykgaWYgX2ljby5leGlzdHMoKSBlbHNlIE5vbmUKCmEgPSBBbmFseXNpcygKICAgIFtzdHIoUEtHX0RJUiAvICJtYWluLnB5IildLAogICAgcGF0aGV4PVtzdHIoUEtHX0RJUildLAogICAgYmluYXJpZXM9W10sCiAgICBkYXRhcz1kYXRhcywKICAgIGhpZGRlbmltcG9ydHM9aGlkZGVuX2ltcG9ydHMsCiAgICBob29rc3BhdGg9W10sCiAgICBob29rc2NvbmZpZz17fSwKICAgIHJ1bnRpbWVfaG9va3M9W10sCiAgICBleGNsdWRlcz1bCiAgICAgICAgInRraW50ZXIiLCAiX3RraW50ZXIiLAogICAgICAgICJQeVF0NSIsICJQeVNpZGUyIiwgIlB5U2lkZTYiLCAid3giLCAiZ2kiLAogICAgICAgICJJUHl0aG9uIiwgImp1cHl0ZXIiLCAibm90ZWJvb2siLAogICAgICAgICJweXRlc3QiLCAic3BoaW54IiwgImRvY3V0aWxzIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX2d0azNhZ2ciLAogICAgICAgICJtYXRwbG90bGliLmJhY2tlbmRzLmJhY2tlbmRfZ3RrM2NhaXJvIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX3d4YWdnIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX3RrYWdnIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5iYWNrZW5kX25iYWdnIiwKICAgICAgICAibWF0cGxvdGxpYi5iYWNrZW5kcy5fYmFja2VuZF90ayIsCiAgICBdLAogICAgbm9hcmNoaXZlPUZhbHNlLAopCgpweXogPSBQWVooYS5wdXJlLCBhLnppcHBlZF9kYXRhKQoKZXhlID0gRVhFKAogICAgcHl6LCBhLnNjcmlwdHMsIFtdLAogICAgZXhjbHVkZV9iaW5hcmllcz1UcnVlLAogICAgbmFtZT0icGxvdHZpeiIsCiAgICBkZWJ1Zz1GYWxzZSwKICAgIGJvb3Rsb2FkZXJfaWdub3JlX3NpZ25hbHM9RmFsc2UsCiAgICBzdHJpcD1GYWxzZSwKICAgIHVweD1GYWxzZSwKICAgIGNvbnNvbGU9RmFsc2UsCiAgICBpY29uPV9pY29uX2FyZywKICAgIHZlcnNpb25fZmlsZT1Ob25lLAopCgpjb2xsID0gQ09MTEVDVCgKICAgIGV4ZSwgYS5iaW5hcmllcywgYS56aXBmaWxlcywgYS5kYXRhcywKICAgIHN0cmlwPUZhbHNlLCB1cHg9RmFsc2UsIHVweF9leGNsdWRlPVtdLAogICAgbmFtZT0icGxvdHZpeiIsCikKIiIiCgpwYXRobGliLlBhdGgoInBsb3R2aXpfd2luLnNwZWMiKS53cml0ZV90ZXh0KHNwZWMubHN0cmlwKCksIGVuY29kaW5nPSJ1dGYtOCIpCnByaW50KCIgIHBsb3R2aXpfd2luLnNwZWMgd3JpdHRlbiIp').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
echo ^> Cleaning previous build...
if exist build                     rmdir /s /q build
if exist "%DIST_DIR%\%APP_NAME%"  rmdir /s /q "%DIST_DIR%\%APP_NAME%"

echo.
echo ^> Building %APP_NAME%.exe...
uv run pyinstaller "%SPEC_FILE%" --noconfirm --clean --log-level WARN
if errorlevel 1 (
    echo [ERROR] PyInstaller build failed.
    echo         Retry: uv run pyinstaller %SPEC_FILE% --noconfirm --clean --log-level DEBUG
    exit /b 1
)

if not exist "%EXE%" (
    echo [ERROR] Build failed -- %EXE% not found.
    exit /b 1
)
echo    %APP_NAME%.exe found.

echo.
echo ^> Writing file-association registry script...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('aW1wb3J0IHBhdGhsaWIKCnJlZyA9IHBhdGhsaWIuUGF0aCgiZGlzdC9wbG90dml6L3JlZ2lzdGVyX2ZpbGV0eXBlcy5yZWciKQpjb250ZW50ID0gKAogICAgIldpbmRvd3MgUmVnaXN0cnkgRWRpdG9yIFZlcnNpb24gNS4wMFxyXG5cclxuIgogICAgIjsgcGxvdHZpeiBmaWxlLXR5cGUgYXNzb2NpYXRpb25zXHJcbiIKICAgICI7IERvdWJsZS1jbGljayB0aGlzIGZpbGUgKG9yIHJ1biBhcyBBZG1pbmlzdHJhdG9yKSB0byByZWdpc3Rlci5cclxuXHJcbiIKICAgICJbSEtFWV9DTEFTU0VTX1JPT1RcXC5wdml6XVxyXG4iCiAgICAiQD1cInBsb3R2aXouQ2hhcnRcIlxyXG5cclxuIgogICAgIltIS0VZX0NMQVNTRVNfUk9PVFxccGxvdHZpei5DaGFydF1cclxuIgogICAgIkA9XCJwbG90dml6IENoYXJ0XCJcclxuXHJcbiIKICAgICJbSEtFWV9DTEFTU0VTX1JPT1RcXHBsb3R2aXouQ2hhcnRcXERlZmF1bHRJY29uXVxyXG4iCiAgICAiQD1cIlxcXCJDOlxcXFxQcm9ncmFtIEZpbGVzXFxcXHBsb3R2aXpcXFxccGxvdHZpei5leGVcXFwiLDBcIlxyXG5cclxuIgogICAgIltIS0VZX0NMQVNTRVNfUk9PVFxccGxvdHZpei5DaGFydFxcc2hlbGxcXG9wZW5cXGNvbW1hbmRdXHJcbiIKICAgICJAPVwiXFxcIkM6XFxcXFByb2dyYW0gRmlsZXNcXFxccGxvdHZpelxcXFxwbG90dml6LmV4ZVxcXCIgXFxcIiUxXFxcIlwiXHJcblxyXG4iCiAgICAiW0hLRVlfQ0xBU1NFU19ST09UXFwucHZpenRdXHJcbiIKICAgICJAPVwicGxvdHZpei5UZW1wbGF0ZVwiXHJcblxyXG4iCiAgICAiW0hLRVlfQ0xBU1NFU19ST09UXFxwbG90dml6LlRlbXBsYXRlXVxyXG4iCiAgICAiQD1cInBsb3R2aXogVGVtcGxhdGVcIlxyXG5cclxuIgogICAgIltIS0VZX0NMQVNTRVNfUk9PVFxccGxvdHZpei5UZW1wbGF0ZVxcRGVmYXVsdEljb25dXHJcbiIKICAgICJAPVwiXFxcIkM6XFxcXFByb2dyYW0gRmlsZXNcXFxccGxvdHZpelxcXFxwbG90dml6LmV4ZVxcXCIsMFwiXHJcblxyXG4iCiAgICAiW0hLRVlfQ0xBU1NFU19ST09UXFxwbG90dml6LlRlbXBsYXRlXFxzaGVsbFxcb3BlblxcY29tbWFuZF1cclxuIgogICAgIkA9XCJcXFwiQzpcXFxcUHJvZ3JhbSBGaWxlc1xcXFxwbG90dml6XFxcXHBsb3R2aXouZXhlXFxcIiBcXFwiJTFcXFwiXCJcclxuXHJcbiIKICAgICI7IC5wdml6eCAtLSBQeXRob24gYnVuZGxlIChzdGFuZGFyZCB6aXApOyBvcGVucyB3aXRoIFdpbmRvd3MgYnVpbHQtaW5cXHJcXG4iCiAgICAiW0hLRVlfQ0xBU1NFU19ST09UXFwucHZpenhdXFxyXFxuIgogICAgIkA9XFwiQ29tcHJlc3NlZEZvbGRlclxcIlxcclxcbiIKICAgICJcXCJQZXJjZWl2ZWRUeXBlXFwiPVxcImNvbXByZXNzZWRcXCJcXHJcXG5cXHJcXG4iCikKcmVnLndyaXRlX3RleHQoY29udGVudCwgZW5jb2Rpbmc9InV0Zi0xNiIpCnByaW50KGYiICB7cmVnfSB3cml0dGVuIik=').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
echo ^> Writing NSIS installer script...
uv run python -c "import base64,pathlib;pathlib.Path('_tmp_build.py').write_text(base64.b64decode('aW1wb3J0IHBhdGhsaWIKCnZlcnNpb24gPSBvcGVuKCJzcmMvcGxvdHZpei9jb25maWcvX3ZlcnNpb24ucHkiKS5yZWFkKCkuc3BsaXQoJyInKVsxXQpuc2kgPSBwYXRobGliLlBhdGgoImRpc3QvaW5zdGFsbGVyLm5zaSIpCgojIE5TSVMgYmFja3RpY2sgc3RyaW5ncyBjYW4gY29udGFpbiBkb3VibGUtcXVvdGVzIHdpdGhvdXQgZXNjYXBpbmcuCiMgYCIkSU5TVERJUlxwbG90dml6LmV4ZSIgIiUxImAgaXMgdGhlIGNvcnJlY3Qgb3Blbi1jb21tYW5kIHN5bnRheC4Kb3Blbl9jbWQgPSAnYCIkSU5TVERJUlxccGxvdHZpei5leGUiICIlMSJgJwoKbGluZXMgPSBbXQphID0gbGluZXMuYXBwZW5kCgphKGYnTmFtZSAicGxvdHZpeiB7dmVyc2lvbn0iJykKYShmJ091dEZpbGUgInBsb3R2aXote3ZlcnNpb259LXNldHVwLmV4ZSInKQphKCdJbnN0YWxsRGlyICIkUFJPR1JBTUZJTEVTNjRcXHBsb3R2aXoiJykKYSgnSW5zdGFsbERpclJlZ0tleSBIS0xNICJTb2Z0d2FyZVxccGxvdHZpeiIgIkluc3RhbGxfRGlyIicpCmEoJ1JlcXVlc3RFeGVjdXRpb25MZXZlbCBhZG1pbicpCmEoJ1NldENvbXByZXNzb3IgL1NPTElEIGx6bWEnKQphKCcnKQphKCchaW5jbHVkZSAiTVVJMi5uc2giJykKYSgnIWRlZmluZSBNVUlfQUJPUlRXQVJOSU5HJykKYSgnIWRlZmluZSBNVUlfSUNPTiAiLi5cXGFzc2V0c1xccGxvdHZpei5pY28iJykKYSgnIWRlZmluZSBNVUlfVU5JQ09OICIuLlxcYXNzZXRzXFxwbG90dml6LmljbyInKQphKCchaW5zZXJ0bWFjcm8gTVVJX1BBR0VfV0VMQ09NRScpCmEoJyFpbnNlcnRtYWNybyBNVUlfUEFHRV9ESVJFQ1RPUlknKQphKCchaW5zZXJ0bWFjcm8gTVVJX1BBR0VfSU5TVEZJTEVTJykKYSgnIWluc2VydG1hY3JvIE1VSV9QQUdFX0ZJTklTSCcpCmEoJyFpbnNlcnRtYWNybyBNVUlfVU5QQUdFX0NPTkZJUk0nKQphKCchaW5zZXJ0bWFjcm8gTVVJX1VOUEFHRV9JTlNURklMRVMnKQphKCchaW5zZXJ0bWFjcm8gTVVJX0xBTkdVQUdFICJFbmdsaXNoIicpCmEoJycpCmEoJ1NlY3Rpb24gInBsb3R2aXogKHJlcXVpcmVkKSIgU2VjTWFpbicpCmEoJyAgU2VjdGlvbkluIFJPJykKYSgnICBTZXRPdXRQYXRoICIkSU5TVERJUiInKQphKCcgIEZpbGUgL3IgInBsb3R2aXpcXCouKiInKQphKCcnKQphKCcgIFdyaXRlVW5pbnN0YWxsZXIgIiRJTlNURElSXFxVbmluc3RhbGwuZXhlIicpCmEoJycpCmEoJyAgV3JpdGVSZWdTdHIgSEtMTSAiU29mdHdhcmVcXE1pY3Jvc29mdFxcV2luZG93c1xcQ3VycmVudFZlcnNpb25cXFVuaW5zdGFsbFxccGxvdHZpeiIgIkRpc3BsYXlOYW1lIiAicGxvdHZpeiInKQphKGYnICBXcml0ZVJlZ1N0ciBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiRGlzcGxheVZlcnNpb24iICJ7dmVyc2lvbn0iJykKYSgnICBXcml0ZVJlZ1N0ciBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiVW5pbnN0YWxsU3RyaW5nIiAiJElOU1RESVJcXFVuaW5zdGFsbC5leGUiJykKYSgnICBXcml0ZVJlZ1N0ciBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiSW5zdGFsbExvY2F0aW9uIiAiJElOU1RESVIiJykKYSgnICBXcml0ZVJlZ1N0ciBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiUHVibGlzaGVyIiAiUGF1bG8gQ2FjaGltIicpCmEoJyAgV3JpdGVSZWdEV09SRCBIS0xNICJTb2Z0d2FyZVxcTWljcm9zb2Z0XFxXaW5kb3dzXFxDdXJyZW50VmVyc2lvblxcVW5pbnN0YWxsXFxwbG90dml6IiAiTm9Nb2RpZnkiIDEnKQphKCcgIFdyaXRlUmVnRFdPUkQgSEtMTSAiU29mdHdhcmVcXE1pY3Jvc29mdFxcV2luZG93c1xcQ3VycmVudFZlcnNpb25cXFVuaW5zdGFsbFxccGxvdHZpeiIgIk5vUmVwYWlyIiAxJykKYSgnJykKYSgnICBDcmVhdGVEaXJlY3RvcnkgIiRTTVBST0dSQU1TXFxwbG90dml6IicpCmEoJyAgQ3JlYXRlU2hvcnRjdXQgIiRTTVBST0dSQU1TXFxwbG90dml6XFxwbG90dml6LmxuayIgIiRJTlNURElSXFxwbG90dml6LmV4ZSInKQphKCcgIENyZWF0ZVNob3J0Y3V0ICIkU01QUk9HUkFNU1xccGxvdHZpelxcVW5pbnN0YWxsLmxuayIgIiRJTlNURElSXFxVbmluc3RhbGwuZXhlIicpCmEoJyAgQ3JlYXRlU2hvcnRjdXQgIiRERVNLVE9QXFxwbG90dml6LmxuayIgIiRJTlNURElSXFxwbG90dml6LmV4ZSInKQphKCcnKQphKCcgIFdyaXRlUmVnU3RyIEhLQ1IgIi5wdml6IiAiIiAicGxvdHZpei5DaGFydCInKQphKCcgIFdyaXRlUmVnU3RyIEhLQ1IgInBsb3R2aXouQ2hhcnQiICIiICJwbG90dml6IENoYXJ0IicpCmEoJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5DaGFydFxcRGVmYXVsdEljb24iICIiICIkSU5TVERJUlxcYXNzZXRzXFxwdml6LmljbyInKQphKGYnICBXcml0ZVJlZ1N0ciBIS0NSICJwbG90dml6LkNoYXJ0XFxzaGVsbFxcb3BlblxcY29tbWFuZCIgIiIge29wZW5fY21kfScpCmEoJycpCmEoJyAgV3JpdGVSZWdTdHIgSEtDUiAiLnB2aXp0IiAiIiAicGxvdHZpei5UZW1wbGF0ZSInKQphKCcgIFdyaXRlUmVnU3RyIEhLQ1IgInBsb3R2aXouVGVtcGxhdGUiICIiICJwbG90dml6IFRlbXBsYXRlIicpCmEoJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5UZW1wbGF0ZVxcRGVmYXVsdEljb24iICIiICIkSU5TVERJUlxcYXNzZXRzXFxwdml6dC5pY28iJykKYShmJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5UZW1wbGF0ZVxcc2hlbGxcXG9wZW5cXGNvbW1hbmQiICIiIHtvcGVuX2NtZH0nKQphKCcnKQphKCcnKQphKCcgIFdyaXRlUmVnU3RyIEhLQ1IgIi5wdml6YyIgIiIgInBsb3R2aXouQ29sb3JTY2hlbWUiJykKYSgnICBXcml0ZVJlZ1N0ciBIS0NSICJwbG90dml6LkNvbG9yU2NoZW1lIiAiIiAicGxvdHZpeiBDb2xvciBTY2hlbWUiJykKYSgnICBXcml0ZVJlZ1N0ciBIS0NSICJwbG90dml6LkNvbG9yU2NoZW1lXFxEZWZhdWx0SWNvbiIgIiIgIiRJTlNURElSXFxhc3NldHNcXHB2aXpjLmljbyInKQphKGYnICBXcml0ZVJlZ1N0ciBIS0NSICJwbG90dml6LkNvbG9yU2NoZW1lXFxzaGVsbFxcb3BlblxcY29tbWFuZCIgIiIge29wZW5fY21kfScpCmEoJyAgV3JpdGVSZWdTdHIgSEtDUiAiLnB2aXpwIiAiIiAicGxvdHZpei5QYWxldHRlQnVuZGxlIicpCmEoJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5QYWxldHRlQnVuZGxlIiAiIiAicGxvdHZpeiBQYWxldHRlIEJ1bmRsZSInKQphKCcgIFdyaXRlUmVnU3RyIEhLQ1IgInBsb3R2aXouUGFsZXR0ZUJ1bmRsZVxcRGVmYXVsdEljb24iICIiICIkSU5TVERJUlxcYXNzZXRzXFxwdml6cC5pY28iJykKYShmJyAgV3JpdGVSZWdTdHIgSEtDUiAicGxvdHZpei5QYWxldHRlQnVuZGxlXFxzaGVsbFxcb3BlblxcY29tbWFuZCIgIiIge29wZW5fY21kfScpCmEoJyAgOyAucHZpenggaXMgYSBzdGFuZGFyZCB6aXAgLS0gcmVnaXN0ZXIgd2l0aCBXaW5kb3dzIGJ1aWx0LWluIHppcCBoYW5kbGVyJykKYSgnICBXcml0ZVJlZ1N0ciBIS0NSICIucHZpengiICIiICJDb21wcmVzc2VkRm9sZGVyIicpCmEoJyAgV3JpdGVSZWdTdHIgSEtDUiAiLnB2aXp4IiAiUGVyY2VpdmVkVHlwZSIgImNvbXByZXNzZWQiJykKYSgnJykKYSgnICBTeXN0ZW06OkNhbGwgInNoZWxsMzI6OlNIQ2hhbmdlTm90aWZ5KGkgMHg4MDAwMDAwLCBpIDAsIGkgMCwgaSAwKSInKQphKCdTZWN0aW9uRW5kJykKYSgnJykKYSgnU2VjdGlvbiAiVW5pbnN0YWxsIicpCmEoJyAgRGVsZXRlICIkSU5TVERJUlxcVW5pbnN0YWxsLmV4ZSInKQphKCcgIFJNRGlyIC9yICIkSU5TVERJUiInKQphKCcgIERlbGV0ZSAiJFNNUFJPR1JBTVNcXHBsb3R2aXpcXHBsb3R2aXoubG5rIicpCmEoJyAgRGVsZXRlICIkU01QUk9HUkFNU1xccGxvdHZpelxcVW5pbnN0YWxsLmxuayInKQphKCcgIFJNRGlyICIkU01QUk9HUkFNU1xccGxvdHZpeiInKQphKCcgIERlbGV0ZSAiJERFU0tUT1BcXHBsb3R2aXoubG5rIicpCmEoJyAgRGVsZXRlUmVnS2V5IEhLTE0gIlNvZnR3YXJlXFxNaWNyb3NvZnRcXFdpbmRvd3NcXEN1cnJlbnRWZXJzaW9uXFxVbmluc3RhbGxcXHBsb3R2aXoiJykKYSgnICBEZWxldGVSZWdLZXkgSEtMTSAiU29mdHdhcmVcXHBsb3R2aXoiJykKYSgnICBEZWxldGVSZWdLZXkgSEtDUiAiLnB2aXoiJykKYSgnICBEZWxldGVSZWdLZXkgSEtDUiAicGxvdHZpei5DaGFydCInKQphKCcgIERlbGV0ZVJlZ0tleSBIS0NSICIucHZpenQiJykKYSgnICBEZWxldGVSZWdLZXkgSEtDUiAicGxvdHZpei5UZW1wbGF0ZSInKQphKCcgIERlbGV0ZVJlZ0tleSBIS0NSICIucHZpemMiJykKYSgnICBEZWxldGVSZWdLZXkgSEtDUiAicGxvdHZpei5Db2xvclNjaGVtZSInKQphKCcgIERlbGV0ZVJlZ0tleSBIS0NSICIucHZpenAiJykKYSgnICBEZWxldGVSZWdLZXkgSEtDUiAicGxvdHZpei5QYWxldHRlQnVuZGxlIicpCmEoJyAgU3lzdGVtOjpDYWxsICJzaGVsbDMyOjpTSENoYW5nZU5vdGlmeShpIDB4ODAwMDAwMCwgaSAwLCBpIDAsIGkgMCkiJykKYSgnU2VjdGlvbkVuZCcpCgpuc2kud3JpdGVfdGV4dCgnXG4nLmpvaW4obGluZXMpLCBlbmNvZGluZz0ndXRmLTgnKQpwcmludChmIiAge25zaX0gd3JpdHRlbiIp').decode(),encoding='utf-8')"
uv run python _tmp_build.py
if errorlevel 1 ( del /f _tmp_build.py 2>nul & exit /b 1 )
del /f _tmp_build.py 2>nul
echo.
set "MAKENSIS="
where makensis >nul 2>&1
if not errorlevel 1 set "MAKENSIS=makensis"
if "%MAKENSIS%"=="" if exist "%PROGRAMFILES%\NSIS\makensis.exe"      set "MAKENSIS=%PROGRAMFILES%\NSIS\makensis.exe"
if "%MAKENSIS%"=="" if exist "%PROGRAMFILES(X86)%\NSIS\makensis.exe" set "MAKENSIS=%PROGRAMFILES(X86)%\NSIS\makensis.exe"

if "%MAKENSIS%"=="" (
    echo ^> makensis not found -- skipping installer.
    echo    Install NSIS from https://nsis.sourceforge.io to build a setup.exe
) else (
    echo ^> Building NSIS installer...
    cd "%DIST_DIR%"
    "%MAKENSIS%" installer.nsi
    cd "%ROOT_DIR%"
    if exist "%INSTALLER_OUT%" (
        echo    %INSTALLER_OUT% created.
    ) else (
        echo    WARNING: NSIS ran but installer not found.
    )
)

echo.
echo ^> Creating portable zip...
if exist "%ZIP_OUT%" del "%ZIP_OUT%"

where powershell >nul 2>&1
if errorlevel 1 (
    where 7z >nul 2>&1
    if errorlevel 1 (
        echo    WARNING: Neither PowerShell nor 7-Zip -- skipping zip.
    ) else (
        7z a -tzip "%ZIP_OUT%" ".\%APP_DIR%\*" >nul
        echo    %ZIP_OUT% created via 7-Zip.
    )
) else (
    powershell -NoProfile -Command "Compress-Archive -Path '%APP_DIR%\*' -DestinationPath '%ZIP_OUT%' -Force"
    echo    %ZIP_OUT% created via PowerShell.
)

echo.
echo ================================================
echo   Build succeeded
echo   EXE     : %EXE%
if exist "%INSTALLER_OUT%" echo   Installer: %INSTALLER_OUT%
if exist "%ZIP_OUT%"       echo   Portable : %ZIP_OUT%
echo.
echo   Test    : %EXE%
echo ================================================
