# -*- mode: python ; coding: utf-8 -*-
"""
plotviz.spec — PyInstaller spec for macOS .app bundle
Location: ~/plotviz/plotviz.spec  (repo root)

Build:
    cd ~/plotviz
    bash build_macos.sh
"""

from pathlib import Path
from PyInstaller.utils.hooks import collect_data_files, collect_submodules
import importlib.util as _ilu

# Read version from the single source of truth
_vspec = Path(SPECPATH) / 'src' / 'plotviz' / 'config' / '_version.py'  # noqa: F821
_vmod  = _ilu.spec_from_file_location('_version', _vspec)
_vm    = _ilu.module_from_spec(_vmod); _vmod.loader.exec_module(_vm)
APP_VERSION = _vm.__version__

# SPECPATH = ~/plotviz/ (where this spec lives)
ROOT_DIR = Path(SPECPATH)                          # noqa: F821
PKG_DIR  = ROOT_DIR / 'src' / 'plotviz'          # where ui/, data/, styling/ live

hidden_imports = [
    # Qt
    'PyQt6', 'PyQt6.QtWidgets', 'PyQt6.QtCore', 'PyQt6.QtGui',
    'PyQt6.QtPrintSupport', 'PyQt6.sip',
    # Matplotlib
    'matplotlib', 'matplotlib.pyplot',
    'matplotlib.backends.backend_qt5agg',
    'matplotlib.backends.backend_qtagg',
    'matplotlib.backends.backend_agg',
    'matplotlib.backends.backend_svg',
    'matplotlib.backends.backend_pdf',
    'matplotlib.figure', 'matplotlib.ticker', 'matplotlib.colors',
    'matplotlib.cm', 'matplotlib.patches', 'matplotlib.lines',
    'matplotlib.collections', 'matplotlib.contour', 'matplotlib.image',
    'matplotlib.axes._axes', 'matplotlib.axes._base',
    'matplotlib.axes._secondary_axes',
    'mpl_toolkits', 'mpl_toolkits.mplot3d',
    'mpl_toolkits.mplot3d.axes3d', 'mpl_toolkits.mplot3d.art3d',
    # numpy
    'numpy', 'numpy.core._multiarray_umath', 'numpy.core.multiarray',
    'numpy.random', 'numpy.fft', 'numpy.linalg',
    # scipy
    'scipy', 'scipy.optimize', 'scipy.stats', 'scipy.interpolate',
    'scipy.special', 'scipy.linalg',
    'scipy._lib.messagestream', 'scipy._lib._util',
    # pandas
    'pandas',
    'pandas._libs.tslibs.np_datetime', 'pandas._libs.tslibs.nattype',
    'pandas._libs.tslibs.timedeltas', 'pandas._libs.tslibs.timestamps',
    'pandas._libs.tslibs.offsets', 'pandas._libs.tslibs.period',
    'pandas._libs.tslibs.timezones', 'pandas._libs.missing',
    'pandas.io.formats.style', 'pandas.io.excel._openpyxl',
    # openpyxl
    'openpyxl', 'openpyxl.cell._writer', 'openpyxl.styles',
    'openpyxl.reader.excel', 'openpyxl.writer.excel',
    'openpyxl.utils', 'openpyxl.utils.dataframe',
    # App packages
    'ui', 'ui.main_window', 'ui.tab_builders', 'ui.plot_engine',
    'ui.serialization', 'ui.canvas', 'ui.python_export', 'ui.seaborn_explorer',
    'data', 'data.loader', 'data.scientific',
    'styling', 'styling.presets',
    'config', 'config.settings', 'config._version',
    # statsmodels (bundled so Robust fit / LOWESS work in .app)
    'statsmodels', 'statsmodels.regression', 'statsmodels.regression.linear_model',
    'statsmodels.nonparametric', 'statsmodels.nonparametric.smoothers_lowess',
    'statsmodels.robust', 'statsmodels.tools',
    # stdlib
    'zipfile', 'json', 'tempfile', 'traceback', 'csv', 'io',
    'multiprocessing', 'multiprocessing.pool',
]

hidden_imports += collect_submodules('matplotlib')
hidden_imports += collect_submodules('mpl_toolkits')
hidden_imports += collect_submodules('scipy')
hidden_imports += collect_submodules('pandas')
hidden_imports += collect_submodules('openpyxl')
hidden_imports += collect_submodules('PyQt6')
hidden_imports += collect_submodules('statsmodels')

datas = []
# Bundle the assets folder (icon etc.) if it exists
_assets = ROOT_DIR / 'assets'
if _assets.exists():
    datas += [(str(_assets), 'assets')]

# Bundle file-type icons into Resources directly so macOS can find them
# These are generated by make_file_icons.py + make_file_icns.sh
for _ft_icns in ['pviz.icns', 'pvizt.icns', 'pvizc.icns', 'pvizp.icns']:
    _ft_path = _assets / _ft_icns
    if _ft_path.exists():
        datas += [(str(_ft_path), '.')]   # lands in Contents/Resources/
datas += collect_data_files('matplotlib')
datas += collect_data_files('mpl_toolkits')
datas += collect_data_files('pandas')
datas += collect_data_files('openpyxl')
datas += collect_data_files('scipy')

a = Analysis(
    [str(PKG_DIR / 'main.py')],
    pathex=[str(PKG_DIR)],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', '_tkinter',
        'PyQt5', 'PySide2', 'PySide6', 'wx', 'gi',
        'IPython', 'jupyter', 'notebook',
        'pytest', 'sphinx', 'docutils',
        'matplotlib.backends.backend_gtk3agg',
        'matplotlib.backends.backend_gtk3cairo',
        'matplotlib.backends.backend_wxagg',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.backends.backend_nbagg',
        'matplotlib.backends._backend_tk',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name='plotviz',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,   # set to 'entitlements.plist' when signing
    icon=str(ROOT_DIR / 'assets' / 'plotviz.icns') if (ROOT_DIR / 'assets' / 'plotviz.icns').exists() else None,
)

coll = COLLECT(
    exe, a.binaries, a.zipfiles, a.datas,
    strip=False, upx=False, upx_exclude=[],
    name='plotviz',
)

app = BUNDLE(
    coll,
    name='plotviz.app',
    icon=str(ROOT_DIR / 'assets' / 'plotviz.icns') if (ROOT_DIR / 'assets' / 'plotviz.icns').exists() else None,
    bundle_identifier='com.pviz.app',
    version=APP_VERSION,
    info_plist={
        'CFBundleName':               'plotviz',
        'CFBundleDisplayName':        'plotviz',
        'CFBundleShortVersionString': APP_VERSION,
        'CFBundleVersion':            APP_VERSION,
        'CFBundleIdentifier':         'com.pviz.app',
        'CFBundleExecutable':         'plotviz',
        'CFBundlePackageType':        'APPL',
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName':        'plotviz Chart',
                'CFBundleTypeExtensions':  ['pviz'],
                'CFBundleTypeRole':        'Editor',
                'LSHandlerRank':           'Owner',
                'CFBundleTypeIconFile':    'pviz.icns',
                'LSItemContentTypes':      ['com.pviz.app.pviz'],
            },
            {
                'CFBundleTypeName':        'plotviz Template',
                'CFBundleTypeExtensions':  ['pvizt'],
                'CFBundleTypeRole':        'Editor',
                'LSHandlerRank':           'Owner',
                'CFBundleTypeIconFile':    'pvizt.icns',
                'LSItemContentTypes':      ['com.pviz.app.pvizt'],
            },
            {
                'CFBundleTypeName':        'plotviz Color Scheme',
                'CFBundleTypeExtensions':  ['pvizc'],
                'CFBundleTypeRole':        'Editor',
                'LSHandlerRank':           'Owner',
                'CFBundleTypeIconFile':    'pvizc.icns',
                'LSItemContentTypes':      ['com.pviz.app.pvizc'],
            },
            {
                'CFBundleTypeName':        'plotviz Palette Bundle',
                'CFBundleTypeExtensions':  ['pvizp'],
                'CFBundleTypeRole':        'Editor',
                'LSHandlerRank':           'Owner',
                'CFBundleTypeIconFile':    'pvizp.icns',
                'LSItemContentTypes':      ['com.pviz.app.pvizp'],
            },
            {
                # .pvizx is a standard zip — declare so Finder names the type,
                # but Alternate rank keeps Archive Utility as the default opener.
                'CFBundleTypeName':        'plotviz Python Bundle',
                'CFBundleTypeExtensions':  ['pvizx'],
                'CFBundleTypeRole':        'Viewer',
                'LSHandlerRank':           'Alternate',
                'LSItemContentTypes':      ['com.pviz.app.pvizx'],
            },
        ],
        'UTExportedTypeDeclarations': [
            {
                'UTTypeIdentifier':        'com.pviz.app.pviz',
                'UTTypeDescription':       'plotviz Chart',
                'UTTypeConformsTo':        ['public.data', 'public.zip-archive'],
                'UTTypeTagSpecification':  {'public.filename-extension': ['pviz']},
                'UTTypeIconFile':          'pviz.icns',
            },
            {
                'UTTypeIdentifier':        'com.pviz.app.pvizt',
                'UTTypeDescription':       'plotviz Template',
                'UTTypeConformsTo':        ['public.data', 'public.zip-archive'],
                'UTTypeTagSpecification':  {'public.filename-extension': ['pvizt']},
                'UTTypeIconFile':          'pvizt.icns',
            },
            {
                'UTTypeIdentifier':        'com.pviz.app.pvizc',
                'UTTypeDescription':       'plotviz Color Scheme',
                'UTTypeConformsTo':        ['public.data', 'public.zip-archive'],
                'UTTypeTagSpecification':  {'public.filename-extension': ['pvizc']},
                'UTTypeIconFile':          'pvizc.icns',
            },
            {
                'UTTypeIdentifier':        'com.pviz.app.pvizp',
                'UTTypeDescription':       'plotviz Palette Bundle',
                'UTTypeConformsTo':        ['public.data', 'public.zip-archive'],
                'UTTypeTagSpecification':  {'public.filename-extension': ['pvizp']},
                'UTTypeIconFile':          'pvizp.icns',
            },
            {
                # .pvizx conforms to public.zip-archive so Archive Utility
                # (and any zip app) can open it natively on macOS.
                'UTTypeIdentifier':        'com.pviz.app.pvizx',
                'UTTypeDescription':       'plotviz Python Bundle',
                'UTTypeConformsTo':        ['public.zip-archive'],
                'UTTypeTagSpecification':  {'public.filename-extension': ['pvizx']},
            },
        ],
        'LSMinimumSystemVersion':     '11.0',
        'LSApplicationCategoryType':  'public.app-category.productivity',
        'NSHighResolutionCapable':    True,
        'NSSupportsAutomaticGraphicsSwitching': True,
        'NSDocumentsFolderUsageDescription':
            'plotviz needs access to open and save chart files.',
        'NSDownloadsFolderUsageDescription':
            'plotviz needs access to open files from Downloads.',
        'NSDesktopFolderUsageDescription':
            'plotviz needs access to files on the Desktop.',
    },
)
